### ISSUE TITLE
Publish on Homebrew

### ISSUE THREAD

**Issue by schickling** [warner/magic-wormhole#1]
I'd love to see this tool available via [Homebrew](https://github.com/Homebrew/homebrew) :+1:

**Comment by warner** [comment]
Yeah, I have some incompatible protocol changes in the works (removing the distinction between "Initiator" and "Receiver", to make things easier), so I'm holding off on publishing it too widely until that stabilizes. And we'll have to see how well my relay server handles the load :). But then yeah, I'll put it up on homebrew. (I don't have any experience with writing Homebrew recipies, feel free to send some hints my way).

**Comment by colinsf** [comment]
:+1: @warner [https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged](they have a how-to guide) that links to the [formula cookbook](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md)

**Comment by grempe** [comment]
There are also additional instructions specific to Python packages:

https://github.com/Homebrew/brew/blob/master/docs/Homebrew-and-Python.md
https://github.com/Homebrew/brew/blob/master/docs/Python-for-Formula-Authors.md

**Comment by tdsmith** [comment]
Will by fixed by https://github.com/Homebrew/homebrew-core/pull/11256!

**Comment by warner** [comment]
Looks like this shipped. At the moment, `brew install magic-wormhole` will get you 0.9.2.
