### ISSUE TITLE
option to receive to a specific file

### ISSUE THREAD

**Issue by joeyh** [warner/magic-wormhole#101]
wormhole receive --accept-file auto-accepts a file transfer. It would be great to extend this so --accept-file=foo (or another different option) could be used to specify exactly where the received file should go.

My use case for this is exchanging data between two peers, so the program that runs wormhole receive will need to load the data from the file. So rather than guessing what file might have been received it would be good to be able to specify it up front.

**Comment by warner** [comment]
Good idea. Does `wormhole rx --accept-file --output-file=foo` do what you need? Perhaps in conjunction with an implementation of #73? I'd be open to making the `--accept-file` unnecessary when you've already provided a filename to `--output-file=`.. I guess we should consider whether auto-clobber is acceptable too, or if there should be a way to automatically accept but *not* clobber.

**Comment by joeyh** [comment]
Brian Warner wrote:
> Good idea. Does wormhole rx --accept-file --output-file=foo do what you need?

Nice way of pointing out I had missed the --output-file option. Yes, it
does just what I needed, when combined with --accept-file. The clobber
check is not a problem.

-- 
see shy jo

**Comment by warner** [comment]
ok, great, closing this one out. Lemme know if the docs could be more clear (currrently `wormhole rx --help` is the only place that reveals this option, but when we get some longer-form prose docs written up, I think "How To Use Magic-Wormhole In Automation Scripts" might be a good section, and `--output-file=` would make a prominent appearance in there).
