### ISSUE TITLE
typing spaces into wormhole code causes an exception

### ISSUE THREAD

**Issue by warner** [warner/magic-wormhole#12]
@gtank noticed that typing in spaces (instead of hyphens) into the wormhole code causes an exception. I'm guessing the readline library (in particular the completion function I wrote) doesn't appreciate those characters.

**Comment by warner** [comment]
```
(ve3) % wormhole-local receive
Enter receive wormhole code: 5 ohio rebirth
main function encountered error
Traceback (most recent call last):
 ...
  File "src/wormhole/wormhole.py", line 456, in _API_input_code
    self._event_learned_code(code)
  File "src/wormhole/wormhole.py", line 482, in _event_learned_code
    raise ValueError("code (%s) must start with NN-" % code)
builtins.ValueError: code (5 ohio rebirth) must start with NN-
```

**Comment by derwolfe** [comment]
When a user enters a code with spaces instead of dashes, would you (@warner) prefer that the user be told that an invalid code was provided and have the application proceed according to that path? Or would you rather have some information be provided to inform the user of a possible mistake regarding spaces vs. dashes?

**Comment by warner** [comment]
The former sounds good (emit a useful error and bail). In the future, we might change this so it only cares when we're using `input_code()` (the interactive tab-completion readline API), and not when the entire code is passed in all-at-once with `set_code()` (to allow codes that actually do have spaces). OTOH, maybe it's safer/easier overall to just declare that wormhole codes never have spaces.

PR looks good, landing. Thanks!
