### ISSUE TITLE
Making wormhole work on cygwin

### ISSUE THREAD

**Issue by fhoshino** [warner/magic-wormhole#13]
Currently, magic-wormhole relies on *nix commands which is not avalible on cygwin, say ifconfig.
Please consider a compatible way to make it work cygwin.

**Comment by warner** [comment]
Does it fail entirely, or does it just fall back to using the transit relay? I *think* it ought to be the latter, which is a performance/cost problem, but shouldn't inhibit the basic functionality. The only unix-specific code should be in the "what are my own IP addresses" library (`src/wormhole/ipaddrs.py`).

(we can probably improve things by having the rendezvous server tell each connecting client what IP address it appears to be coming from, and use that as a hint, which will be correct for directly-connected clients, and will point to the exterior of a NAT box for NAT-bound clients)

**Comment by fhoshino** [comment]
No, it will not fallback

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/wormhole/cli/cli.py", line 99, in _dispatch_command
    yield maybeDeferred(command)
AssertionError: ifconfig
ERROR: ifconfig

**Comment by warner** [comment]
@fhoshino could you try the latest git trunk? That commit I just pushed ought to fix the issue. Thanks!

**Comment by fhoshino** [comment]
ok, it works after the lasteset trunk and installing back a few dependencies.

➜  temp wormhole receive
Warning: errors may occur unless both sides are running the same version
Server claims 0.8.2 is current, but ours is 0.8.2+5.g123073a
Enter receive wormhole code: 5-antenna-ahead
Receiving file (39 Bytes) into: redir.json
ok? (y/n): y
Receiving (->relay:tcp:wormhole-transit.lothar.com:4001)..
100%|████████████████████████████████████████████████████| 39.0/39.0 [00:00<00:00, 128KB/s]
Received file written to redir.json
