### ISSUE TITLE
add Tor support for py3

### ISSUE THREAD

**Issue by warner** [warner/magic-wormhole#136]
The current limitation is that `txsocksx` is incompatible with python3, and `txtorcon` depends upon `txsocksx`, and magic-wormhole's Tor support requires `txtorcon`.

@meejah and others tell me that `txsocksx` is not likely to be fixed any time soon, but that he's got a txtorcon branch that replaces it with something else. So the next step for this ticket is probably to help him get that branch landed.

**Comment by meejah** [comment]
BTW, the socks stuff from that branch landed and got released in `0.18.0`. I'm currently landing other fun stuff from that branch on master (e.g. the `Tor` object). **Most** stuff except the onion/hidden services improvements/refactorings (and API-breakage) have landed.

No APIs were harmed in the merging of these features (AFAIK).

master is now being tested against py2.7, py3 and pypy on twisted 15 and 16 (and Very Soon 17).

**Comment by meejah** [comment]
I'll probably do a release before dealing with the onion stuff, but I want to make sure the new APIs introduced are .. fully baked before I do a release and have to live with them.

The documentation got more-or-less re-written, too, so is hopefully easier to follow now.

**Comment by meejah** [comment]
Since txtorcon 0.9.0 was released, full Python3 support is available in txtorcon (0.9.1 fixed a regression in `launch_tor()`). (Also the `txsocksx` dependency has been dropped).

**Comment by warner** [comment]
Manual testing confirms that `--tor` and `--launch-tor` now work on py3. Yay!

In a separate issue we can consider whether to make `txtorcon` a regular dependency, and remove the `[tor]` "extra".
