### ISSUE TITLE
Tab completion not working on Windows

### ISSUE THREAD

**Issue by brianpburns** [warner/magic-wormhole#137]
Using wormhole in Windows, both in Windows command prompt and in Cygwin, tab completion does not work. Both terminals just appear to insert a tab character.

**Comment by warner** [comment]
Does tab completion work in other readline-based applications? Especially the python REPL loop, when you turn on tab-completion with `$PYSTARTUP` and the suggestions in https://docs.python.org/2.5/tut/node15.html ?

**Comment by brianpburns** [comment]
I can't get it working anywhere, so I guess it's a problem with my environment.
