### ISSUE TITLE
pip install failed on Ubuntu 16.04

### ISSUE THREAD

**Issue by bitcartel** [warner/magic-wormhole#142]
Ubuntu 16.04
gcc version 5.4.0
Python 2.7.12

```
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1089, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by warner** [comment]
I think we need more to go on (was there any stderr from the compiler?), but it sounds like you might be missing the `python-dev` or `build-essential` packages. Or maybe something else that's providing a necessary .h file, like `libffi-dev` or `libssl-dev` or something.

**Comment by taigrr** [comment]
@warner I can confirm it is a missing Python.h file. Installing python-dev or python3-dev fixes the issue (depending on whether you're using pip or pip3)

YOu can probably close this issue :)

**Comment by warner** [comment]
Ok, thanks for the followup!
