### ISSUE TITLE
wordlist vs _wordlist

### ISSUE THREAD

**Issue by exarkun** [warner/magic-wormhole#146]
There's a `_wordlist.py` in the repository and no `wordlist.py` afaict.

Importing `wormhole.codes` fails:

```
>>> import wormhole.codes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../magic-wormhole/src/wormhole/codes.py", line 3, in <module>
    from .wordlist import (byte_to_even_word, byte_to_odd_word,
ImportError: No module named wordlist
>>>
```

**Comment by warner** [comment]
oops, `wormhole.codes` should be removed entirely.. that functionality moved into _wordlist (and more specifically into the completion helper API). I'll land a patch to do that now (and WONTFIX #147).

Do you need something exposed to generate codes? There's nothing in the new implementation to expose the wordlist directly, but maybe we could add something. Take a look in docs/api.md and see if the existing stuff does what you want, or if we should add something new.
