### ISSUE TITLE
Php version of Server

### ISSUE THREAD

**Issue by taigrr** [warner/magic-wormhole#148]
Hey there,

This might be too large of an undertaking, but here's the rub:

Servers are easy and cheap, but servers with root access + a compiler are not, hence it's not possible to run the server on every machine.

I'd definitely help out with hosting (running a secondary server) if there were a php version available (or ruby or perl even) and i'm sure plenty of others would too. 

I say this because your server costs maybe not be high right now, But I'm in the process of developing a GUI client for desktop and an Android port as well, and you might eventually see a spike in usage.

Perhaps you could start a new branch with a rewrite in PHP? I'd definitely help where I can.

**Comment by taigrr** [comment]
My Gui ports would do something like this to ensure all clients work together:

```
Sender:
	Send on both servers
Receiver:
	 If connection is found
		Prompt user to save file
	Else
		Try next relay
Sender:
	close other connection
	continue sending on whichever relay handshake occurred on
exit
```

**Comment by exarkun** [comment]
It seems like the ongoing maintenance costs of a PHP implementation might actually exceed the operational costs of more servers.  Perhaps there's some other reason to have a PHP server (the only one that really comes to mind though is "people who like hacking on PHP would like to have such a thing to hack on") but it doesn't seem like cost would be one of them.

**Comment by taigrr** [comment]
Perhaps, but some hosts allow unlimited execution of php and provide unlimited disk space and bandwidth, but do not allow python installs. This is in fact my particular use case.

**Comment by warner** [comment]
I'm going to close this one.. I greatly appreciate the interest, but I agree with exarkun that maintaining a PHP version of the Rendezvous Server represents more work than running multiple instances of the python-backed server.

Enhancing the client to correctly handle multiple servers (issue #72) *is* a worthwhile change, as we need it for ad-hoc networks (#48). But in that case, the new rendezvous server will be run by one or both of the client nodes, so it will need to be implemented in the same language, and I don't think a PHP version of the *client* is in the cards any time soon.

I think the "Transit Relay" component might be a better candidate for implementation in other languages. That's the part which is going to need scaling first, and the runtime cost is all bandwidth (the CPU and storage needs are minimal, but the relay server will spend all of its time ferrying bytes from one socket to another). So a PHP version might indeed help us take advantage of cheap servers which limit what languages you get to use. I wouldn't consider it to be a high priority, given how little servers cost these days, but it'd be a "nice to have".

This would be the code in https://github.com/warner/magic-wormhole/blob/0.9.2/src/wormhole/server/transit_server.py , which runs the protocol documented in https://github.com/warner/magic-wormhole/blob/master/docs/transit.md . I don't know much about PHP, but I suspect it wouldn't be too happy about the raw TCP sockets that the protocol uses right now. OTOH I think we may need to change that anyways (to make the relay usable by web-based clients that can only do HTTP).
