### ISSUE TITLE
python -m wormhole

### ISSUE THREAD

**Issue by kurtbrose** [warner/magic-wormhole#159]
In addition to the CLI entrypoints and python API, it would be nice if `python -m wormhole` did the same thing as `wormhole`.  (Or, possibly `python -m wormhole.cli`.)

This can be implemented incredibly easily by adding `__main__.py`.

There are two uses for this:

1- Development of wormhole itself without having to `pip install` it.

2- Users path may be messed up, but being able to specify e.g. `/usr/bin/python36 -m wormhole` removes ambiguity.  For example, if you are currently inside a virtualenv, or doing a `docker exec -it bash`.

As evidence that this is a reasonable idea, both `pytest` and `pip` have both a CLI interface and a `python -m` interface.

If you agree that this is a good idea I'd be happy to provide a PR, the implementation is extremely simple.

**Comment by warner** [comment]
Yeah, that sounds like a great idea. PR please!

**Comment by kurtbrose** [comment]
https://github.com/warner/magic-wormhole/pull/163

**Comment by warner** [comment]
closed by #163
