### ISSUE TITLE
Transit shouldn't suggest 127.0.0.1

### ISSUE THREAD

**Issue by warner** [warner/magic-wormhole#16]
The Transit object, in `.get_connection_hints()`, returns a list of IP addresses (gleaned by running `ifconfig`) that the other side should connect to. We should probably strip out `127.0.0.1` from the list, because that is only ever useful when both host are running on the same machine, which only ever happens for developer tests.

(it might be nice to have a flag to turn this back on, for the test suite, but for normal CLI use, 127.0.0.1 it isn't helpful)

**Comment by higs4281** [comment]
working on it

**Comment by warner** [comment]
The patch looks pretty good, but the windows (appveyor) build is failing in a weird way. Maybe the VMs they use don't have anything other than 127.0.0.1? I think I'll make a separate branch, that prints out all the addresses that it finds, to detect that.

**Comment by warner** [comment]
Closed by 3f05cd3007812606633b3b1a4cc3df56b119a6d1 and PR #36. Thanks!
