### ISSUE TITLE
Automatically build magic-wormhole Docker images on Docker Hub

### ISSUE THREAD

**Issue by exarkun** [warner/magic-wormhole#167]
There's a Dockerfile in the repository now.  We just need to configure Docker Hub with an automated build for the project.  I'm volunteering to do this.  I just need access to whatever Docker Hub namespace we want to publish the image in.

I have my personal Docker Hub account, "exarkun", of course.  And I have access to the "leastauthority" organization.  I could set either of these up today without additional help.  Neither of these seems like quite the right place, though.

I see there is a "dockertahoe" user which publishes a "tahoe-lafs" image.  This might be a good place.  I'm not sure who actually controls the "dockertahoe" user though. Also, an organization would be easier to manage than a user (users can be converted into organizations, I believe).

Also, there is a "tahoelafs" user publishing "base" and ""node" images.  This might also be a good place.  The same comments apply here as to "dockertahoe" above, though.

**Comment by exarkun** [comment]
I created a Docker Hub organization to hold this image and can share access (by granting permissions to that repo/org to other Docker Hub users).  However, I was unable to set up an automated build for magic-wormhole because this requires configuring hooks in the magic-wormhole GitHub project. :/  So I think right now only @warner can do this (either directly or by re-arranging permissions on magic-wormhole, eg by inviting some admin collaborators or moving magic-wormhole to a github org with other members).

**Comment by warner** [comment]
I *think* we've got this running now.. is there anything else we need to do before closing this ticket?

(we might want to split out the server into a separate package, maybe, and then only have the server components in the docker image. But maybe there's value to having a client implementation as an image too?)

**Comment by exarkun** [comment]
I think what we've got is pretty good as a first pass.  I'm sure the image can be improved in various ways - but we can figure that out as folks actually try to use it, I think.  I'm going to go ahead and close this.  Thanks!
