### ISSUE TITLE
always depend upon txtorcon? (remove the [tor] extra)

### ISSUE THREAD

**Issue by warner** [warner/magic-wormhole#174]
As mentioned in #136, now that txtorcon works on py3 in addition to py2, we could change our setup.py to unconditionally depend upon it, instead of limiting it's use to the `[tor]` extra. We'd remove it from `extras_require=` and move it into the normal `install_requires=`.

**Comment by meejah** [comment]
In my experience, the "extras" aren't very discoverable, especially for "end users". I feel okay having a "dev" extra in txtorcon's setup.py but these days try to avoid any extras.

When there *are* optional dependencies, I think it's better to catch the import error and tell the user something useful (e.g. "to use the --tor option, you must install 'txtorcon'. Try 'pip install txtorcon'"). Obviously, this could instead suggest "pip install magic-wormhole[tor]" if you keep the optional extra.

If this affects your decision, txtorcon *will* continue to support Py2 and Py3 for the indefinite future.

**Comment by warner** [comment]
As best I can tell, txtorcon no longer adds any dependencies beyond what magic-wormhole itself uses (I see `automat` and `ipaddress` and `twisted`, which we use directly, and also `incremental` and `zope.interface`, which Twisted also uses). And `txtorcon` is pure-python, and it isn't terribly huge (the `.whl` is  about 300kB). So I don't think we lose anything by making it mandatory
