### ISSUE TITLE
Allow command-line configuration of the location of relay.sqlite and stats.json

### ISSUE THREAD

**Issue by exarkun** [warner/magic-wormhole#184]
It's operationally more complicated to have relay.sqlite, stats.json, and twistd.pid all in the same directory.

Let me do something like:

    $ wormhole-server start --relay-database-path /foo/bar.sqlite --stats-path /baz/stats.json

It wouldn't hurt to have an option for the location of the pid file but at worst that can always be controlled via working directory.

**Comment by warner** [comment]
-0 for my own needs, but if you've got a use for that, I'm willing to land a patch.

**Comment by warner** [comment]
closed by #186 in 9413edac
