### ISSUE TITLE
16 bits of wormhole code entropy is not secure

### ISSUE THREAD

**Issue by tbodt** [warner/magic-wormhole#191]
If an attacker starts 65534 wormhole send requests, they then know exactly what wormhole code is going to be used by the next user to start a send request.

**Comment by exarkun** [comment]
Each wormhole is separate from the rest.  Each wormhole has a nameplate.  Nameplates are randomly allocated from the range 1..1000000 (though with smaller nameplates preferred when possible).  

The nameplates identify a mailbox which can be used to exchange messages between clients.

Separately from the nameplate, each wormhole has a couple random words (currently taken from the PGP word list).  The two words provide 16 bits of entropy by themselves.  The words are not known to the rendezvous server.

To open a wormhole, a client encrypts some details into a mailbox for the nameplate they're using.  A client who wishes to have the other side of the wormhole must use the same mailbox and the same random words.  One guess is allowed per mailbox.  If the guess is wrong, that wormhole is ruined and the first client must begin again.

Thus, to reliably guess the nameplate of the next client (and thus gain access to the mailbox that client will use), the attacker must start 1000000-1 wormholes.  Having forced the next client to use a particular nameplate which the attacker can predict, the attacker must now also guess the magic words that client has selected (1 in 2^16 chance).  They have one guess and if it is wrong the wormhole is destroyed.

So, apart from resource exhaustion and denial of service issues, attackers aren't helped by flooding the rendezvous server with many spurious wormholes.

**Comment by alex-davidson** [comment]
Judging by the usage instructions, it appears that the 'magic word' alone is enough to identify and authorise a pending transfer.

https://en.wikipedia.org/wiki/Birthday_attack

If the 'magic word' entropy is only 16 bits, then with only 36 concurrent wormholes on the same rendezvous server there is a 1% probability of a collision by sheer chance. This rises to 25% with 190 concurrent wormholes.

**Comment by exarkun** [comment]
Perhaps the docs don't make the distinction between the nameplate and the magic words clear enough.  Altogether, they make up the "wormhole code" - but the magic words by themselves represent the 16 bits of entropy.  The birthday attack is prevented by the fact that you have to declare in advance which nameplate you're using.  Your guess is applied to exactly one (potential) wormhole.  It doesn't matter how many concurrent wormholes there are at the time of the guess.  The guess is only applied to the wormhole associated with the nameplate you selected and if you guess wrong that potential wormhole is ruined and the process must begin again.

**Comment by alex-davidson** [comment]
Ah, so the wormhole code includes the nameplate and contains more than just 16 bits of entropy, and the nameplate is allocated from a pool and therefore is not subject to random collisions. 

With a pool of only a million nameplates that yields only 20+16=36 bits, but only permitting a single attempt per nameplate along with the (comparatively) very slow human in the loop does indeed seem to discourage even opportunistic brute force attacks.

Nice!

**Comment by warner** [comment]
Yup, the wormhole code consists of the nameplate (aka channel id aka the numeric part), and the secret words. The entropy comes from the words, since the nameplate is necessarily revealed to the server. The nameplate is allocated from a server-managed pool, which randomly chooses the shortest available number (so if there are fewer than 10 channels open, it will return a single-digit nameplate).

The recipient (and attacker) gets exactly one guess per nameplate, and the attacker's chance of success depends entirely upon the entropy of the words (the number of nameplates doesn't figure into it).

I'm guessing this concern is resolved.. I'm going to close this, but I'll try to improve the docs to make it more clear what's going on, since I've heard this concern from multiple people. Obviously we're not explaining it very well :).

**Comment by DurandA** [comment]
It is unclear to me what is the link between the *mailbox_id* and the nameplate.
```
def generate_mailbox_id():
    return base64.b32encode(os.urandom(8)).lower().strip(b"=").decode("ascii")
```

Explanations are much appreciated!
