### ISSUE TITLE
Is this an alternative to robocopy + ssh to cron backups offsite (dropbox'ish style)?

### ISSUE THREAD

**Issue by cottsak** [warner/magic-wormhole#193]

**Comment by warner** [comment]
I'm not familiar with robocopy, but from what I've been able to find on it, I think the answer is no.

As I understand it, robocopy gets you:
* recursive copies of directories
* some sort of network copy (it appears to include bandwidth limiting)
* the ability to resume from interrupted transfers
* skipping target files that appear identical (same size+timestamps)
* delete target files that were removed from the source

Magic-wormhole only gets you one-shot copies of a file or directory. You could wrap it a cron job to get repeated copies, but it will refuse to overwrite target files that already exist (unless you override that), and it makes no attempt to utilize partial data that's already at the destination. It won't delete anything.

Robocopy sounds a lot like `rsync` in the unix world, and `rsync` also does a lot of clever things to minimize the bandwidth used when the target already looks mostly like the source. To use `rsync` securely, you need to run it over `ssh`, for which you need a public key on the far end (but magic-wormhole is a great way to deliver that pubkey: check out `wormhole ssh accept` and `wormhole ssh invite`).

And neither approach protects you against the backup host seeing your files. For client-side encryption of backups, take a look at https://tahoe-lafs.org (I'm also an author).

Hope that answers your question!
