### ISSUE TITLE
Allow configuration of (some) WebSocket protocol options from server CLI

### ISSUE THREAD

**Issue by exarkun** [warner/magic-wormhole#196]
There are a lot of knobs on a WebSocket server that can be turned to various effect.

For example, Autobahn WebSockets have an "auto ping" feature which can be used as a connection keep-alive feature.

These knobs seem to be controlled by a `setProtocolOptions` method on the factory.

**Comment by exarkun** [comment]
https://autobahn.readthedocs.io/en/latest/websocket/programming.html#websocket-options

**Comment by warner** [comment]
Sounds good.. I'll land the related patch. I'd like to treat this as temporary, though. In the longer run (after the server is split out into a separate package, and some other cleanups happen), we should remove the argv controls in favor of a config file.

**Comment by exarkun** [comment]
Just as a potential discussion point ... Command line args and environment variables have ended up the least-effort way to control software that gets put into Docker containers because it's typically trivial to control those two inputs to a process.  Making a configuration file available requires a lot more effort - either creating the file and providing it as host-mount (or possibly other kind of) volume or building a wrapper around the entrypoint that itself knows about argv or env and generates a configuration file on the fly.
