### ISSUE TITLE
wormhole: command not found

### ISSUE THREAD

**Issue by ilmoralito** [warner/magic-wormhole#207]
Hi. I getting the message _wormhole: command not found_ in a fresh and free of errors installation in ubuntu 16.04 LTS. Thanks for any idea

**Comment by meejah** [comment]
How did you install it? Did you activate the virtualenv in the shell you're trying to run `wormhole` in?

**Comment by ilmoralito** [comment]
Thanks for answering and I have not activated it, I followed the installation guide and probe. What could be the next step?

**Comment by meejah** [comment]
What have you done thus far; it's not clear which instructions you followed?

**Comment by ilmoralito** [comment]
I followed the installation instructions https://github.com/warner/magic-wormhole#installation

**Comment by meejah** [comment]
That doesn't include explicit virtualenv instructions, though. So you did the `apt-get` commands, and then what?

**Comment by ilmoralito** [comment]
I Run the commands in this order:

> sudo apt-get install python-pip build-essential python-dev libffi-dev libssl-dev
> pip install magic-wormhole

At this point i got a message about upgrade pip

So i run 

> pip install --upgrade pip

This last step i do not know if it is relevant

After that i tried sending a file

> wormhole send somefile.txt

And i get _wormhole: command not found_ message

**Comment by meejah** [comment]
You should upgrade pip and then install wormhole. Also, there is no virtualenv involved in your above steps (perhaps pip defaults to using `--user` on Ubuntu? I do not know). Try this:

```
virtualenv venv
source venv/bin/activate
pip install --upgrade pip setuptools
pip install magic-wormhole
wormhole --help
```

**Comment by ilmoralito** [comment]
It works.

When I try to send a file after a while I get this message

> wormhole send Roshiandkids.png
ERROR: We had a problem connecting to the relay server:
(relay URL was ws://relay.magic-wormhole.io:4000/v1)
User timeout caused connection failure.

Firewall I guess

**Comment by thehackercat** [comment]
@ilmoralito I have the same problem, so how do u solve this at the end ? Set up some http proxy or disable the firewall?

**Comment by meejah** [comment]
Most firewalls should allow HTTP traffic; perhaps it is sad about the non-default port (4000 instead of 80 or 443)?

**Comment by BirkhoffLee** [comment]
@meejah The government of People's Republic of China has a internet censorship called Great FireWall which has blocked your relay servers. Is it possible to use wormhole with proxies?

**Comment by ysig** [comment]
@meejah I also installed under a university server which has a known proxy and just running wormhole send yields the same error. Why doesn't it pick up the proxy and send it through it? (it's both set on HTTP_PROXY and HTTPS_PROXY)

**Comment by meejah** [comment]
@ysig I made your comment a new issue. Please feel free to add more details if you have :)
