### ISSUE TITLE
order of configuration and compilation

### ISSUE THREAD

**Issue by ManYsha** [warner/magic-wormhole#222]
i am new to python and I want to know how to run this code . can anyone help me how to do it, mean the steps to be followed to execute the code and the topics to be known to get a clarity about Magic wormhole application?

**Comment by warner** [comment]
Welcome to python! What operating system are you using? Did you take a look at the "Installation" section of the README?

**Comment by ManYsha** [comment]
Yes sir,i read README.md and im using Windows 8

**Comment by ManYsha** [comment]
When I execute 'pip install ' command it's showing me some error

**Comment by warner** [comment]
Could you paste in the error that you got?

**Comment by ManYsha** [comment]
its showing syntax error.Is that mandetory to install virtualenv?

**Comment by warner** [comment]
Using a virtualenv is a good idea, to keep magic-wormhole and its dependencies from interfering with the rest of your system.

Please paste in the error that you got. I cannot guess what kind of syntax error that you might have run into.

**Comment by warner** [comment]
closing this one.. I don't think we can help without more information. sorry!
