### ISSUE TITLE
Cannot import name attrs(Windows)

### ISSUE THREAD

**Issue by shacker101** [warner/magic-wormhole#224]
![03](https://user-images.githubusercontent.com/29296553/28276202-be2b48e0-6b48-11e7-8c99-3c3bdcda38f5.png)
When I installed some mistakes:
![01](https://user-images.githubusercontent.com/29296553/28276216-caa0a444-6b48-11e7-83bf-0199770c8c59.png)
![02](https://user-images.githubusercontent.com/29296553/28276219-d206aff8-6b48-11e7-8df8-82748327bdb1.png)
![03](https://user-images.githubusercontent.com/29296553/28276225-d653f124-6b48-11e7-9052-1db01f2f855f.png)
I installed VCForPython27 when I saw the promote.
Please forgive my bad English.

**Comment by miracle3212** [comment]
@shacker101 Is that PowerShell for building wormhole packages ? Try Cygwin then, or keep your works going and check [some prerequisites if missing](https://0x12345.blogspot.com/2017/07/files-transfer-w-wormhole-cross-platform.html)

**Comment by warner** [comment]
I *think* this should be fixed in current trunk, in 68ce54ad3a99d412d4886fddc94a5f38a79777d6, which adds `attrs` as a dependency. I'm not sure what was going on with your install, but having all the right dependencies can't hurt.
