### ISSUE TITLE
snap packaging is self-reporting the wrong version string

### ISSUE THREAD

**Issue by warner** [warner/magic-wormhole#234]
I started playing with the "snappy" packaging yesterday (and I have to say it's pretty cool.. I had no idea how it worked before, the namespace-based isolation is pretty slick). But I noticed that `wormhole --version` reports the wrong thing:

```
warner@snaptest2:~$ sudo snap install wormhole
...
warner@snaptest2:~$ wormhole --version
magic-wormhole 0.10.2+0.g13ff246.dirty
```

magic-wormhole uses [Versioneer](https://github.com/warner/python-versioneer) to manage the version string, which makes the setup.py run `git describe` to figure out what's in the source tree, and processes that to determine the version string. When setup.py is asked to make a build artifact (like `setup.py sdist` or `setup.py wheel`), it embeds this generated string into one of the source files (`src/wormhole/_version.py`) so all non-git-checkout source trees derived from that artifact will get the right version.

I'm guessing the snap build process is modifying one of the non-ignored source files, and then `setup.py` is invoked, so it thinks the tree is dirty, and creates a version string with that `+0.g13ff246.dirty` suffix.

One way to fix this might be to have the snap build process start by making an sdist or a wheel (`python setup.py sdist`), and then install from that. The filename will be somewhat unpredictable, but maybe something like `pip install dist/magic-wormhole*` would work, assuming it's run in a clean checkout with no other .tar.gz files in `dist/` already. Or maybe there's a way to tell `setup.py sdist` to write the output to a specific filename.

Or, if we could figure out what's being modified, maybe there's a way to make it stop.

@elopio , what do you think? I've only just started looking at the snapcraft documentation, so I'm not sure what's the best way to address this one.

**Comment by elopio** [comment]
Hello @warner! I'm so happy that you are liking it.

There could be a bug in snapcraft, because the snapcraft.yaml file is not being copied from the repo to the `parts/magic-wormhole/build` directory, where pip install is called. I will be back at work on tuesday, and I'll bring this up to discuss with my teammates.

In the meantime, what do you think of my temporary hack in #236? :)

**Comment by warner** [comment]
It sounds reasonable.. although I don't have a good way to test it right now, and I don't think we have any CI set up yet to automatically build .snap packages upon each commit (I'll file a separate bug to discuss that). I'll land this and then later we can figure out whether it actually worked or not :)
