### ISSUE TITLE
snap packaging version should come from Versioneer

### ISSUE THREAD

**Issue by warner** [warner/magic-wormhole#235]
The `snapcraft.yaml` packaging control file has a line that says `version: git`, which is good because it means I don't need to manually update a version string inside `snapcraft.yaml` each time I do a release. We use Versioneer on the setup.py, which means I don't have to update a version string there either: I just `git tag` and push.

It'd be nice if the snapcraft version always matched the setup.py version. They're computed in very similar ways (they both use some flavor of `git describe`), but in a perfect world they'd always be identical.

@elopio: is there any way to tell `snapcraft.yaml` to run a script to learn what version it should use? It could just use the output of `setup.py --version`.

**Comment by elopio** [comment]
We have `version-script`. I think it will do what you want. PR is coming...
