### ISSUE TITLE
Good stuff, but installation instructions for Ubuntu < 17.04 are wrong

### ISSUE THREAD

**Issue by CottonEaster** [warner/magic-wormhole#249]
Instead of 

```
$ apt-get install python-pip build-essential python-dev libffi-dev libssl-dev
$ sudo apt install magic-wormhole
```

You should have

```
$ sudo apt-get install python-pip build-essential python-dev libffi-dev libssl-dev
$ pip install magic-wormhole
```

Oh: but perhaps that is what you say already. Perhaps. The instructions really could be clearer!

**Comment by CottonEaster** [comment]
Also, when I try to run wormhole, I get this:

```
Traceback (most recent call last):
  File "/usr/local/bin/wormhole", line 7, in <module>
    from wormhole.cli.cli import wormhole
  File "/usr/local/lib/python2.7/dist-packages/wormhole/__init__.py", line 6, in <module>
    from .wormhole import create
  File "/usr/local/lib/python2.7/dist-packages/wormhole/wormhole.py", line 3, in <module>
    from attr import attrs, attrib
ImportError: cannot import name attrs
```
I am on Mint 18.3 x64 Cinnamon.

But, ah, I see that [that error has come up already](https://github.com/warner/magic-wormhole/issues/198). I mistakenly sudoed `pip` . .

**Comment by warner** [comment]
I'll add some more `sudo`s to the README instructions, thanks for the catch. And the `attrs` problem is fixed in trunk (in 68ce54ad3a99d412d4886fddc94a5f38a79777d6), so the next release should fix that problem. I'll try to make a new release today.

Thanks!

**Comment by CottonEaster** [comment]
> I'll add some more sudos to the README instructions

Well, just to be clear:

- we need `sudo` for `apt-get install python-pip build-essential python-dev libffi-dev libssl-dev`
- and it is important to omit `sudo` for `pip install magic-wormhole`.

Also, (1) I think people would like to know more about the server and its security, and (2) that server might indeed (for you envisage as much) be apt to get overloaded, no?

**Comment by CottonEaster** [comment]
Also: forgive me, but how does one set up the progam via git? I cloned the repository, made some files executable and tried to run setup.py but . . no dice.

**Comment by warner** [comment]
Yup, that's the sudo I added (see https://github.com/warner/magic-wormhole/commit/0a762c5bfd2ce86d240c56c04c83d573c6a30c5d for the diff). I'll add another note about virtualenvs and avoiding sudo.

The server is documented in the docs/ directory.. look at introduction.md and server-protocol.md . It could get overloaded, sure, is there anything special we should document about that fact?

I'll add a patch momentarily that expands the ``Development`` section of the README to explain setting up a git checkout. Basically you want to create a virtualenv, and run ``pip install .`` from the git checkout.

**Comment by CottonEaster** [comment]
> It could get overloaded, sure, is there anything special we should document about that fact?

Ideally you would have a live, or semi-live, indicator of the server load, or a link to some such indicator.

As to git cloning: OK, good, but, myself, I think I'll wait for the next actual release!
