### ISSUE TITLE
add dependency on twisted[windows_platform] when on windows, or on pypiwin32

### ISSUE THREAD

**Issue by warner** [warner/magic-wormhole#25]
Let's use the new PEP-508 syntax to declare a dependency on whatever windows-specific things we need (pypiwin32, I think) when we're building on windows.

**Comment by meejah** [comment]
https://www.python.org/dev/peps/pep-0508/

**Comment by warner** [comment]
That PR makes the windows instructions be `pip install magic-wormhole[windows]`. The next step is to use the PEP-508 syntax instead of the `[windows]` extra.

**Comment by warner** [comment]
Fixed by a03c1804f7d4f6eff1150cb0ba4d730503c7d3b4 and PR #41. Thanks!
