### ISSUE TITLE
Error transfering directory if it's specified with a trailing slash (bash-for-windows)

### ISSUE THREAD

**Issue by alex** [warner/magic-wormhole#251]
From the sending side:

```
$ wormhole send win32k-ng/
Building zipfile..
Sending directory (1.6 kB compressed) named ''
On the other computer, please run: wormhole receive
Wormhole code is: 8-almighty-blackjack

TransferError: remote error, transfer abandoned: transfer rejected
```

From the receiving side:

```
~/p/h/w/x ❯❯❯ wormhole recv
Enter receive wormhole code: 8-almighty-blackjack
Error: refusing to overwrite existing ''
TransferError: transfer rejected
```

The problem is the trailing slash in `wormhole send win32k-ng/`, if I specify `wormhole send win32k-ng` it works fine.

The fix is probably to `path.strip("/")` if `os.path.isdir(path)` on the sending side.

**Comment by warner** [comment]
Huh, what version are you running? This works for me, on linux, on 0.10.2 (and current trunk). There's a `what = what.rstrip(os.sep)` on line 246 of `src/wormhole/cli/cmd_send.py` that's supposed to handle this case.

**Comment by alex** [comment]
This was magic-wormhole 0.10.2; I have just upgraded to 0.10.3 and the same problem reproduces.

FWIW, the sending side is a Windows machine, but using bash-for-windows, and I specified the path with as `win32k-ng/`, not `win32k-ng\`, I'm not sure what layer of the stack normalizes the slash, but that seems like a potential issue.

**Comment by warner** [comment]
Ah. What is `os.sep` in that environment?

**Comment by warner** [comment]
Also, does `os.path.normpath()` or `realpath()` or `abspath()` know how to clean that up? Or is the specialness of `/` in that environment known only to `open()`?

**Comment by alex** [comment]
```
$ python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.sep
'\\'
>>> path = "win32k-ng/"
>>> os.path.normpath(path)
'win32k-ng'
>>> os.path.realpath(path)
'c:\\mozilla-source\\mozilla-central\\win32k-ng'
>>> os.path.abspath(path)
'c:\\mozilla-source\\mozilla-central\\win32k-ng'
>>>
```

**Comment by warner** [comment]
@alex hey, could you experiment with the 251-slash branch a bit? The normpath() code in cmd_send.py is how I want to do things, but for some reason the new test is failing on windows. I'm away from a windows box right now, if you've got something you can interact with, could you see if you can figure out why it's failing? And also see if that branch 1: works for you on bash-for-windows, and 2: fixes the trailing-slash case. Thanks!

**Comment by alex** [comment]
@warner Sorry it took so long, I've confirmed that it fixes the bug described here.

**Comment by warner** [comment]
Cool, thanks. Now I have to figure out why the test fails on windows so we can land it...

**Comment by warner** [comment]
Ok, turns out that windows `os.path.normpath()` is implemented in terms of `realpath()`, because windows-py2 didn't have a working `islink()` function. Windows-py3 *does*, but `normpath()` wasn't updated to use it, so the fallback is still in place (https://bugs.python.org/issue9949 covers this issue).

I'm going to stick with `normpath()` for now, even though it'll cause incorrect behavior on windows/py3 when you have a funky maze of symlinks and a path that includes `\..\` components, because the situation isn't very common, and because I'm more interested in fixing the trailing-slash/backslash problem that this #251 bug is about. Hopefully we can eventually find a way that fixes both bugs at the same time.
