### ISSUE TITLE
--tor-control-port= is broken

### ISSUE THREAD

**Issue by warner** [warner/magic-wormhole#252]
rxcomm noticed that using `--tor-control-port=` is broken: using it always causes `wormhole` to fall back to using the default SOCKS port.

It appears that `txtorcon.connect(tor_control_port=)` doesn't accept a string, only one of:

* an endpoint instance
* a sequence of endpoint instances
* None, meaning try the usual suspects (`unix:/var/run/tor/control`, `tcp:127.0.0.1:9051`, `tcp:127.0.0.1:9151`)

So the fix is probably just having `wormhole.tor_manager.get_tor` render the argv value into an endpoint with `endpoints.clientFromString()` before passing it into `txtorcon.connect()`.

**Comment by meejah** [comment]
I could probably be convinced txtorcon should accept a string there and just call `clientFromString` on it (bubbling out any exceptions)...

**Comment by warner** [comment]
Eh, I'm happy to change it on the calling side. That API already takes enough types :)

**Comment by meejah** [comment]
So what's one more? ;)

I guess right now the only "real" things it takes are `IEndpoints` which makes sense.
