### ISSUE TITLE
Rendezvous server doesn't close websockets cleanly

### ISSUE THREAD

**Issue by jml** [warner/magic-wormhole#264]
It should send a websockets close handshake with a status code, as per:  https://tools.ietf.org/html/rfc6455#section-7.1.2 

The RFC seems to imply that it's optional to do so, but I'd welcome the change, as other websocket libraries assume a connection that TCP closes without the handshake has closed uncleanly, and raise awkward exceptions.

**Comment by warner** [comment]
This is on the server side, right? Not the client side? I've observed lingering TCP connections on both the rendezvous and transit servers (just using `netstat`), but I haven't been able to track them down.

Can you tell if `rendezvous_websocket.py` is failing to call some necessary Autobahn API, or is there something going wrong inside Autobahn itself?

**Comment by jml** [comment]
Yes, server-side. I can't rule out bugs in Autobahn, and I'm no expert in its use, but probably `rendezvous_websocket.py` needs to call [sendClose](https://autobahn.readthedocs.io/en/latest/reference/autobahn.websocket.html#autobahn.websocket.interfaces.IWebSocketChannel.sendClose). This appears to trigger an internal state change in the websocket protocol which (I'm guessing) triggers a TCP close.

**Comment by warner** [comment]
Hm. It looks like the server never intentionally closes a connection: it lets the client decide when the conversation has finished. The CLOSE message (client->server) delivers the "mood", and unsubscribes from the mailbox, but doesn't affect the websocket connection. (OPEN/CLOSE refer to mailboxes and mailbox subscriptions, not the underlying connection).

Where are you seeing the awkward exceptions?

**Comment by warner** [comment]
Sorry, you said server-side. Could you paste one? I'm not seeing any in the logs of the production rendezvous server. Or are you saying that a client is getting into an awkward state when the TCP connection is dropped without the right websocket code appearing first?

**Comment by jml** [comment]
Actually, I think this is completely invalid. The client should probably call `sendClose`, but it's not a serious bug.
