### ISSUE TITLE
report client version to mailbox server

### ISSUE THREAD

**Issue by warner** [warner/magic-wormhole#287]
I've avoided doing this so far, but I think I need to have the client report its version to the mailbox/rendezvous server so I can measure new-release uptake. I don't currently have any visibility at all into what versions people are running, and I expect it'll help me plan out deprecation of old API versions if I knew what percentage of clients were capable of speaking the new versions.

My plan is to add a "version" key to the BIND message (which is the first message that clients send to the server upon each websocket connection). The value will be a 2-tuple of (implementation, version), with `("python", "0.10.5")` being the current value. The server will record (side, implementation, version, rounded_time) in the usage database, and tooling will de-duplicate `side` before aggregating the results (to avoid double-counting clients which lose their websocket connection and have to make a new one). (`side` is a random string, mostly used to avoid talking to ourselves, but also for deciding which side is the "leader" and which is the "follower" in the upcoming Dilation protocol).

**Comment by Baeumla** [comment]
I'm working on this right now. 

Do you think it is enough to just send `("python", "0.10.5")` or should we also include the python-version the client is using with `sys.version` instead of only the implementation `"python"`?

**Comment by warner** [comment]
Thanks for grabbing this one!

I'd just do `("python", "0.10.5")`. Let's add a table for developers somewhere that says`"python"` means `github.com/warner/magic-wormhole` (or wherever else it ends up living), and if someone starts an independent python implementation then we can call that one `python2` or `python-$authorname` or whatever (i.e. the word "python" is more of a pointer to the particular implementation, rather than implying that the language it's implemented in is particularly important).

Use `wormhole.__version__` for the second string, that'll get updated by Versioneer automatically.

We'll need code on the mailbox/rendezvous-server side to add the two versions (one for each side of a successful connection) into the Usage database. That'll be tracked in https://github.com/warner/magic-wormhole-mailbox-server/issues/3 . But the server will ignore any unrecognized keys in API messages, so we can add this to the client completely independently of it being actually used by the server.

I'm now on the fence about whether to send a 2-tuple or to merge the strings together first (`python-0.10.5`), but I guess it's better to send the 2-tuple and let the server decide how it's going to record the data.

**Comment by warner** [comment]
Done. Thanks!
