### ISSUE TITLE
Transfers are failing with a timeout error

### ISSUE THREAD

**Issue by stormdragon2976** [warner/magic-wormhole#288]
I just started noticing this yesterday. Any time I try to send something, I get the following error:

Traceback (most recent call last):
Failure: twisted.internet.error.TimeoutError: User timeout caused connection failure.
ERROR: User timeout caused connection failure.

I haven't changed any port settings or anything, so I don't think it is anything on my side. I have tried sending to multiple recipients and it fails every time.

**Comment by reckoner** [comment]
I am having the exact same problem!

**Comment by warner** [comment]
Is it working now? I discovered that the transit-relay machine had some sort of kernel crash, and was offline for about six days between Feb-25 and Mar-02 (and I didn't have enough monitoring in place to be notified). If both sides were behind NAT/firewalls, then they'll depend upon the relay to connect, and I think the symptom might be that TimeoutError.

We could probably use a better error message, maybe at least something that points to the relay server as the one that's failing.

**Comment by stormdragon2976** [comment]
Everything is working fine now.

This event does make me curious though. Would it be possible to make it so that the servers used could be configured in a file, possibly in ~/.config/magic-wormhole/wormhole.conf?

Also, is it very difficult to set up a server? Say on a VPS?

**Comment by warner** [comment]
There's no config file, but you can pass `--transit-helper=` to make it use something other than `tcp:transit.magic-wormhole.io:4001`. Both sides (sender and receiver) tell the other one about their configured transit helper, so they can be different (and whichever one they can both reach first will be used).

Running a server is pretty easy: take a look at the https://github.com/warner/magic-wormhole-transit-relay repo for the code. It's published in PyPI as "magic-wormhole-transit-relay", and it's `pip`-installable, but we launch it with Twisted's server-running tools (so `twistd` to run it as a background daemon, or `twist` to run without daemonization).

hope that helps!

**Comment by k4th4rin4** [comment]
@warner I am seeing the exact same error and can't receive my sent file. Would you be so kind to check if the transit server is up and running? Thanks a lot!
