### ISSUE TITLE
sha256 is relatively expensive

### ISSUE THREAD

**Issue by ThomasWaldmann** [warner/magic-wormhole#299]
All data is hashed using sha256 to compare the hash on both sides in the final handshake.

Just wanted to note that sha256 is relatively slow / expensive to compute and (somewhat counter-intuitively) even sha512 is much faster (on 64bit platforms and not much slower on 32bit platforms). If one just wants 256bits, one can just throw away half of the sha512 result.

Also there are more modern crypto hashes like blake2 which are even faster, but maybe not that widely available yet as packages for misc. platforms (so that might require to bundle the blake2 code).

This maybe does not matter much as long as one only has little data to transfer or the transmission channel is slow or the CPU is fast.

I don't know how easy it would be to change the hash without running into compatibility problems, so feel free to close this ticket if it is not an option.

**Comment by warner** [comment]
Yeah, hash speeds can be weird sometimes :). My 2012 mac (2.6GHz Core-i7) runs `shasum -a 256` at 163MBps (so maybe 1.3Gbps). We hash the data as we send it (and as we receive it), so I'm pretty sure the hashing time will be completely hidden by the network latency, unless you're on a platform that has a really slow CPU but some sort of hardware TCP assist that lets it get a really fast transfer despite the CPU.

For the future, we could have a negotiation phase to the protocol (both sides advertise the hashes they support, one side picks their favorite), and yeah I'd probably lean towards Blake2 as an option over sha512, but I don't think the added protocol complexity is a win at this point.

thanks!
