### ISSUE TITLE
Does not compile on Windows due to pyNaCl

### ISSUE THREAD

**Issue by cdhagmann** [warner/magic-wormhole#3]
As per the issue on [pyNaCl](https://github.com/pyca/pynacl/issues/100), it doesn't compile on Windows and, as such, neither does this. Where is pyNaCl used? I wanted to take a look to see if it could be easily replace with libnacl or something, but I am having a hard time locating it.

**EDIT**
I found a use of pyNaCl, but only in the twisted.transcribe. If that is all, could pyNaCl be removed for the required and put on the list of needed if you want "To run a relay server or use the async support, you must also install Twisted and pyNaCL."

**Comment by warner** [comment]
pynacl (in particular the symmetric-key `SecretBox`) is used to encrypt all data in the wormhole library, regardless of the sync/async entry point used. `python-spake2` gets us a key, `HKDF` is used to derive keys specific to each transfer, then `pynacl` encrypts the actual data. That includes both the text in `wormhole send-text`, and the stream of file data in `wormhole send-file`. (you'll find it in `wormhole.blocking.transcribe` too).

I prefer the NaCl crypto routines over e.g. OpenSSL, but that's a bummer that it doesn't compile on windows. Is there a better python binding to the nacl library that *does* work on windows?

**Comment by cdhagmann** [comment]
libnacl is a lightweight alternative that does compile on windows and has [SecretBox](http://libnacl.readthedocs.org/en/latest/topics/secret.html)

**Comment by warner** [comment]
[This one](https://pypi.python.org/pypi/libnacl/1.4.3), right? I didn't know about that one, thanks for the pointer.

It looks like I can `pip install libnacl` fine, but then when I try to import it, I get an OSError about not finding the actual library. pynacl includes its own copy, to avoid this. Any idea if there's a way to get straight-pip installs of libnacl without needing to include instructions for installing the .so/.dylib/.whatever first?

**Comment by cdhagmann** [comment]
I've been trying for a bit and I haven't had any luck. It might be easier to look into why pyNaCl is having the issue, or figure out what part of it magic-wormhole specifically need as it seems like you are well versed in pyNaCl. From my initial check, the necessary parts for wormhole seem to compile alright, but just not all of pyNaCl.

**Comment by AraHaan** [comment]
I did get pynacl to compile before on python 3.5 but not on 3.6 alpha 3.
https://bpaste.net/show/8ce6de33504b

**Comment by warner** [comment]
Looking at https://github.com/pyca/pynacl/issues/100 it seems like the current pynacl-1.0.1 (released about a year ago) ought to be working on windows, and there are windows-specific binary wheels published (so windows users won't even require a compiler, at least not for pynacl).

I think we can close this one as a result. If anyone knows differently, please let us know.

**Comment by sergeevabc** [comment]
Could you be so kind to generate ```.exe``` for the rest of us who use Windows w/o Python?
I’m told that [py2exe][1] or [nuitka][2] might help you to achieve that.

[1]: http://py2exe.org/
[2]: http://nuitka.net/

**Comment by warner** [comment]
Good idea.. I've opened #173 to track that task.
