### ISSUE TITLE
New release for 3.7 fix?

### ISSUE THREAD

**Issue by reaperhulk** [warner/magic-wormhole#310]
There hasn't been a release since the 3.7 fix (https://github.com/warner/magic-wormhole/commit/45315136021b9cdfdfa77eb85bfaaf9677e9f256) was landed. This, unfortunately, means that users of magic-wormhole on homebrew will run into this bug when sending multiple files at once if they have upgraded their python to 3.7 (which homebrew will prompt you, but not force you, to do).

Homebrew prefers to have releases rather than backport patches so it'd be great if we could do a 0.10.6 for at least this fix.

**Comment by warner** [comment]
Oops.. thanks for the reminder. 0.11.0 is now up on PyPI.
