### ISSUE TITLE
pypi long-description isn't rendering properly

### ISSUE THREAD

**Issue by warner** [warner/magic-wormhole#316]
We tried to fix this in #304, but for some reason it isn't rendering on pypi properly:

![screenshot_2018-11-13 magic-wormhole](https://user-images.githubusercontent.com/27146/48431893-b7e85e80-e727-11e8-9c02-7832900e04b3.png)

@mgedmin says some other projects had a similar problem, and it turned out to be a broken version of `twine` used for the upload. I use twine, but I think I upgraded to the current twine-1.12.1 just before making the upload for magic-wormhole-0.11.0 .

**Comment by warner** [comment]
I guess I'll upload an 0.11.1 and see if it helps. Maybe something was broken on pypi itself at that time.

**Comment by mgedmin** [comment]
Perhaps also check the versions of setuptools and wheel?

**Comment by warner** [comment]
hrmph, I uploaded 0.11.1 and the render is still broken.

```
$ twine --version
twine version 1.12.1 (pkginfo: 1.4.2, requests: 2.20.1, setuptools: 40.6.2,
requests-toolbelt: 0.8.0, tqdm: 4.28.1)
```

I reinstalled `twine` into a virtualenv (with `pipsi`) just before doing the upload, and that virtualenv's contents all appear up-to-date:
```
$ ~/.local/venvs/twine/bin/pip list
Package           Version   
----------------- ----------
bleach            3.0.2     
certifi           2018.10.15
chardet           3.0.4     
docutils          0.14      
idna              2.7       
pip               18.1      
pkginfo           1.4.2     
Pygments          2.2.0     
readme-renderer   24.0      
requests          2.20.1    
requests-toolbelt 0.8.0     
setuptools        40.6.2    
six               1.11.0    
tqdm              4.28.1    
twine             1.12.1    
urllib3           1.24.1    
webencodings      0.5.1     
wheel             0.32.2    
```

**Comment by mgedmin** [comment]
`twine check dist/*` can be used to check the validity of long_description fields, at least when they use ReStructuredText.  I don't see any errors from it, so maybe it can't check markdown?  (But markdown is a very forgiving format, I don't even know if it's possible to have syntax errors in it.)

I'm stumped.

Do you use IRC?  People in #pypi on irc.freenode.net might have advice.

**Comment by mgedmin** [comment]
I've found your problem.

If you download magic_wormhole-0.11.1-py2.py3-none-any.whl from https://pypi.org/project/magic-wormhole/#files and unzip it, inside you'll find a magic_wormhole-0.11.1.dist-info/WHEEL that says

> Generator: bdist_wheel (0.29.0)

You need wheel >= 0.31.0 for markdown descriptions.

**Comment by warner** [comment]
Ahh.. yes, I used `/usr/bin/python` for that, and my debian "stretch" box had `python-wheel-0.29.0` installed from .deb . I'll update my notes to use a local (virtualenv) python instead, which will have a newer wheel.

**Comment by warner** [comment]
Ok, 0.11.2 is up, and pypi looks correct now.

Thanks for chasing that one down! I would never have thought about the system's python getting an old version of `wheel` as being the problem.
