### ISSUE TITLE
Speed issue

### ISSUE THREAD

**Issue by electroheadfx** [warner/magic-wormhole#325]
All my receive file is around 450kb/s and the sender can up to 2MB/s, is there is a config setup to break the limit download ? (its PC/MacOS connection) thanks

**Comment by warner** [comment]
I've seen transfers happen at up to 10-20MBps, so I can't think of any obvious limitation. There's no configuration for speed controls.

 The speed *does* depend upon both sides of the connection, so if the sender can do 2MB/s, but the receiver can't maintain that speed, then the overall transfer will run at the minimum of the two sides' connections. It could either be their network connection, or their CPU speed to run the python code.
