### ISSUE TITLE
switch confirm-receive prompt default to "yes"?

### ISSUE THREAD

**Issue by warner** [warner/magic-wormhole#330]
As @morrieinmaas mentioned in #327, it's a bit surprising that, in addition to typing "wormhole receive" and the code, you *also* have to say "yes" (or "y") at the confirmation prompt.

I made it default to "no" because I figured this is the last chance to protect yourself against an unexpectedly huge download, or with a filename that's going to be surprising (some dot file with scary side effects). But really, it's unlikely that you're going to say no after coming all this way.

So I think maybe in the next release we could switch this to a default "yes". Users still have a chance to bail out once they see the filename/size, but they'd have to type more to escape at that point.

**Comment by morrieinmaas** [comment]
Cool, sounds good :+1:  thanks for taking the time
