### ISSUE TITLE
Failed to install on Debian Stretch: pip3, virtualenv, apt

### ISSUE THREAD

**Issue by novoid** [warner/magic-wormhole#336]
Here is my journey of installing on Debian GNU/Linux 9 (stretch) until I gave up.

I don't expect you to fix this since I only wanted to see how this thing is working. I gave up for the moment and not intend to try it again. However, if you think I should test something, let me know.

So if you don't like my feedback, close this issue and forget about me.

If not, here is my story:

-------------------

Install like I use to install: system-wide

``` example
sudo pip3 install --user magic-wormhole
```

installed packages

```
\[…\]  
Installing collected packages: hkdf, spake2, pycparser, cffi,  
pynacl, attrs, automat, tqdm, humanize, PyHamcrest, cons tantly,  
hyperlink, incremental, zope.interface, asn1crypto, cryptography,  
pyasn1-modules, service-identity, twisted, t xtorcon, click,  
txaio, autobahn, magic-wormhole  
Successfully installed PyHamcrest-1.9.0 asn1crypto-0.24.0 attrs-19.1.0
autobahn-19.7.1 automat-0.7.0 cffi-1.12.3 click  
-7.0 constantly-15.1.0 cryptography-2.7 hkdf-0.0.3 humanize-0.5.1
hyperlink-19.0.0 incremental-17.5.0 magic-wormhole-0  
.11.2 pyasn1-modules-0.2.5 pycparser-2.19 pynacl-1.3.0
service-identity-18.1.0 spake2-0.8 tqdm-4.32.2 twisted-19.2.1 t  
xaio-18.8.1 txtorcon-19.0.0 zope.interface-4.6.0
```

stupid me: copy/paste error. `--user` as root only installs for root
only of course :-(

``` example
sudo pip3 install magic-wormhole
```

"already satisfied"? Hm.

getting rid of it again:

``` example
sudo pip3 uninstall magic-wormhole
```

Installing:

``` example
sudo pip3 install magic-wormhole
[...]
Successfully installed magic-wormhole-0.11.2
```

However, doesn't work:

```
vk@sherri \~ % wormhole receive  
Traceback (most recent call last):  
    File "/usr/local/bin/wormhole", line 7, in \<module\>  
    from wormhole.cli.cli import wormhole  
    File
"/usr/local/lib/python3.5/dist-packages/wormhole/\_~init~\_\_.py", line
1, in \<module\>  
    from .~rlcompleter~ import input~withcompletion~  
    File
"/usr/local/lib/python3.5/dist-packages/wormhole/~rlcompleter~.py", line
8, in \<module\>  
    from twisted.internet.defer import inlineCallbacks, returnValue  
ImportError: No module named 'twisted'  
1 vk@sherri \~ %
```

trying to fix:

```
vk@sherri \~ % sudo pip3 install twisted
Requirement already satisfied: twisted in
*root*.local/lib/python3.5/site-packages  
Requirement already satisfied: PyHamcrest\>=1.9.0 in
*root*.local/lib/python3.5/site-packages (from twisted)  
Requirement already satisfied: Automat\>=0.3.0 in
*root*.local/lib/python3.5/site-packages (from twisted)  
Requirement already satisfied: hyperlink\>=17.1.1 in
*root*.local/lib/python3.5/site-packages (from twisted)  
Requirement already satisfied: attrs\>=17.4.0 in
*root*.local/lib/python3.5/site-packages (from twisted)  
Requirement already satisfied: constantly\>=15.1 in
*root*.local/lib/python3.5/site-packages (from twisted)  
Requirement already satisfied: zope.interface\>=4.4.2 in
*root*.local/lib/python3.5/site-packages (from twisted)  
Requirement already satisfied: incremental\>=16.10.1 in
*root*.local/lib/python3.5/site-packages (from twisted)  
Requirement already satisfied: six in /usr/lib/python3/dist-packages
(from PyHamcrest\>=1.9.0-\>twisted)  
Requirement already satisfied: setuptools in
/usr/lib/python3/dist-packages (from PyHamcrest\>=1.9.0-\>twisted)  
Collecting idna\>=2.5 (from hyperlink\>=17.1.1-\>twisted)  
  Downloading
<https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474>  
c9/idna-2.8-py2.py3-none-any.whl (58kB)  
    100% \|¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦\| 61kB 826kB/s  
Installing collected packages: idna  
  Found existing installation: idna 2.2  
    Not uninstalling idna at /usr/lib/python3/dist-packages, outside
environment /usr  
Successfully installed idna-2.8  
vk@sherri \~ % wormhole  
Traceback (most recent call last):  
  File "/usr/local/bin/wormhole", line 7, in \<module\>  
    from wormhole.cli.cli import wormhole  
  File
"/usr/local/lib/python3.5/dist-packages/wormhole/\_~init~\_\_.py", line
1, in \<module\>  
    from .~rlcompleter~ import input~withcompletion~  
  File
"/usr/local/lib/python3.5/dist-packages/wormhole/~rlcompleter~.py", line
8, in \<module\>  
    from twisted.internet.defer import inlineCallbacks, returnValue  
ImportError: No module named 'twisted'  
1 vk@sherri \~ %
```

… did not fix the issue :-(

trying to get rid of everything again and start from scratch:

``` example
sudo pip3 uninstall hkdf spake2 pycparser cffi pynacl attrs automat tqdm humanize PyHamcrest cons tantly hyperlink incremental zope.interface asn1crypto cryptography pyasn1-modules service-identity twisted t xtorcon click txaio autobahn magic-wormhole
```

Installing as user:

``` example
pip3 install --user magic-wormhole
```

… fails:

```
vk@sherri \~ % pip3 install –user magic-wormhole
Traceback (most recent call last):  
  File "/usr/bin/pip3", line 9, in \<module\>  
    from pip import main  
ImportError: cannot import name 'main'  
1 vk@sherri \~ %
```

``` example
sudo pip3 install magic-wormhole
```

still results in missing "twisted"

again: uninstalling everything

for god's sake: install using virtualenv as descibed on README although
I still don't get the practical use of virtualenv idea (activating something before I may use a command?):

``` example
vk@sherri ~ % virtualenv venv
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/vk/venv/bin/python2
Also creating executable in /home/vk/venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
vk@sherri ~ % source venv/bin/activate
130 vk@sherri ~ %
```

stupid thing used Python2 :-(

installing via Debian package:

```
vk@sherri \~ % sudo apt install magic-wormhole  
Reading package lists… Done  
Building dependency tree  
Reading state information… Done  
The following additional packages will be installed:  
  python3-attr python3-autobahn python3-cbor python3-cffi python3-click
python3-colorama python3-constantly  
  python3-hkdf python3-humanize python3-incremental python3-lz4
python3-msgpack python3-nacl python3-ply  
  python3-pyasn1-modules python3-pycparser python3-serial
python3-service-identity python3-snappy python3-spake2  
  python3-tqdm python3-trollius python3-twisted python3-twisted-bin
python3-txaio python3-zope.interface  
Suggested packages:  
  python-attr-doc python-nacl-doc python-ply-doc python3-wxgtk3.0 \|
python3-wxgtk python3-tk python3-gtk2  
  python3-glade2 python3-qt4 python3-wxgtk2.8 python3-twisted-bin-dbg
python-txaio-doc  
Recommended packages:  
  python3-pam  
The following NEW packages will be installed:  
  magic-wormhole python3-attr python3-autobahn python3-cbor python3-cffi
python3-click python3-colorama  
  python3-constantly python3-hkdf python3-humanize python3-incremental
python3-lz4 python3-msgpack python3-nacl  
  python3-ply python3-pyasn1-modules python3-pycparser python3-serial
python3-service-identity python3-snappy  
  python3-spake2 python3-tqdm python3-trollius python3-twisted
python3-twisted-bin python3-txaio  
  python3-zope.interface  
0 upgraded, 27 newly installed, 0 to remove and 11 not upgraded.  
Need to get 2,766 kB of archives.  
After this operation, 17.0 MB of additional disk space will be used.
```

still facing an error, this time, a new one:

```
vk@sherri \~ % wormhole receive  
Traceback (most recent call last):  
  File "/usr/local/bin/wormhole", line 7, in \<module\>  
    from wormhole.cli.cli import wormhole  
  File
"/usr/local/lib/python3.5/dist-packages/wormhole/\_~init~\_\_.py", line
2, in \<module\>  
    from .wormhole import create, <span class="underline"><span
class="underline">version</span></span>  
  File "/usr/local/lib/python3.5/dist-packages/wormhole/wormhole.py",
line 10, in \<module\>  
    from .~boss~ import Boss  
  File "/usr/local/lib/python3.5/dist-packages/wormhole/~boss~.py", line
8, in \<module\>  
    from automat import MethodicalMachine  
ImportError: No module named 'automat'  
1 vk@sherri \~ %
```

getting rid of everything again:

``` example
sudo apt purge magic-wormhole python3-attr python3-autobahn python3-cbor python3-cffi python3-click python3-colorama python3-constantly python3-hkdf python3-humanize python3-incremental python3-lz4 python3-msgpack python3-nacl python3-ply python3-pyasn1-modules python3-pycparser python3-serial python3-service-identity python3-snappy python3-spake2 python3-tqdm python3-trollius python3-twisted python3-twisted-bin python3-txaio python3-zope.interface
```

I give up.

**Comment by warner** [comment]
Ouch. I'm sorry that was so painful, and ultimately unsatisfying :(.

Was the initial `sudo pip3 install --user magic-wormhole` successful? I'd hazard a guess that some files installed during that step were left in place (i.e. maybe `sudo pip3 uninstall magic-wormhole`, without the `--user`, does not remove all of the files installed by a `pip3 install` *with* the `--user`). And that maybe they were interfering with your later attempts, like enough metadata was left around to make it think that wormhole was already installed.

I don't have a lot of experience with doing a system-wide install that's not in a debian package. I guess I've had enough problems like your story, and now I shy away from that approach. The usual issue is that system-wide installs via pip will interact with other system-wide installs (including regular debian packages that happen to use python). So there's the risk of conflicts between dependencies of those two categories of applications, since `pip` and `apt` don't coordinate anything.

I think you came really close when you did `apt install magic-wormhole`. It probably worked, but I see that the subsequent `wormhole receive` error message was using `/usr/local/bin/wormhole` (which must be leftover from an earlier install attempt). The debian package will provide `/usr/bin/wormhole`. I bet if you did `sudo rm /usr/local/bin/wormhole` and `sudo apt install magic-wormhole`, then it might start working.

Incidentally, I have the same concern about virtualenvs when I started using them (having to activate something before I could run a command). I learned that the scripts installed into a virtualenv have their `#!` shbang line changed to point at the python within the virtualenv, so they remember their environment. You could install magic-wormhole into a virtualenv and then make a symlink from `~/bin/wormhole` or `/usr/local/bin/wormhole` to `.../venv/bin/wormhole` and it would work without the "activate" step. The only time I use "activate" is when I'm doing development.

If you ever find you want to give wormhole another try, I'd look at that system for leftover pieces of the previous installs: search for `wormhole` or `magic-wormhole` directories in `/usr/local/lib/python*`, `~/.local/lib/python*`, and `/root/.local/lib/python*`. Also `wormhole` executables in the corresponding `bin` directories. Remove the ones you find, then do `sudo apt install magic-wormhole` and rely on the debian maintainers to get all the dependencies right :).

Good luck, and thanks for giving it a try. I appreciate the feedback!

**Comment by novoid** [comment]
Hi,

-   I found wormhole stuff in global Python 3.5 folders:
    -   /usr/local/lib/python3.5/dist-packages/wormhole
    -   removed via `pip3 uninstall magic-wormhole` since
        `pip3 uninstall
             --user magic-wormhole` did not exist:



    root@sherri ~ # pip3 uninstall --user magic-wormhole

    Usage:
      pip uninstall [options] <package> ...
      pip uninstall [options] -r <requirements file> ...

    no such option: --user
    2 root@sherri ~ #

Trying to install as recommended via `apt install magic-wormhole`:

    root@sherri ~ # apt install magic-wormhole
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    The following packages were automatically installed and are no longer required:
      libasound2:i386 libbsd0:i386 libdbus-1-3:i386 libexpat1:i386 libfontconfig1:i386 libfreetype6:i386 libgcrypt20:i386 libgpg-error0:i386 libice6:i386 libjpeg62-turbo:i386 liblz4-1:i386 libpng12-0:i386
      libpng16-16:i386 libsm6:i386 libsystemd0:i386 libx11-6:i386 libxau6:i386 libxcb1:i386 libxdamage1:i386 libxdmcp6:i386 libxext6:i386 libxfixes3:i386 libxi6:i386 libxinerama1:i386 libxrandr2:i386
      libxrender1:i386 libxtst6:i386
    Use 'sudo apt autoremove' to remove them.
    The following additional packages will be installed:
      python3-attr python3-autobahn python3-cbor python3-cffi python3-click python3-colorama python3-constantly python3-hkdf python3-humanize python3-incremental python3-lz4 python3-msgpack python3-nacl
      python3-ply python3-pyasn1-modules python3-pycparser python3-serial python3-service-identity python3-snappy python3-spake2 python3-tqdm python3-trollius python3-twisted python3-twisted-bin python3-txaio
      python3-zope.interface
    Suggested packages:
      python-attr-doc python-nacl-doc python-ply-doc python3-wxgtk3.0 | python3-wxgtk python3-tk python3-gtk2 python3-glade2 python3-qt4 python3-wxgtk2.8 python3-twisted-bin-dbg python-txaio-doc
    Recommended packages:
      python3-pam
    The following NEW packages will be installed:
      magic-wormhole python3-attr python3-autobahn python3-cbor python3-cffi python3-click python3-colorama python3-constantly python3-hkdf python3-humanize python3-incremental python3-lz4 python3-msgpack
      python3-nacl python3-ply python3-pyasn1-modules python3-pycparser python3-serial python3-service-identity python3-snappy python3-spake2 python3-tqdm python3-trollius python3-twisted python3-twisted-bin
      python3-txaio python3-zope.interface
    0 upgraded, 27 newly installed, 0 to remove and 11 not upgraded.
    Need to get 2,766 kB of archives.
    After this operation, 17.0 MB of additional disk space will be used.

Now it works:

    vk@sherri ~2d % wormhole send test.txt
    Sending 12 Bytes file named 'test.txt'
    On the other computer, please run: wormhole receive
    Wormhole code is: 6-adroitness-kickoff

    [...]


Thanks for the very competent answer. I learned a few things.

Unfortunately, I can't test a full testrun before September. I assume, it now works so I close this issue.

**Comment by nobrowser** [comment]
But ... I would *really* like to run my own relay. In fact I think that's the only way I'll start using `wormhole`. And my server distro at the moment (devuan ascii) has no relay packages, only client packages. (Does the relay depend on `systemd`, maybe indirectly? That would be a reason for no devuan package.) So, how can I install the relay code and run it? The extreme plan would be to create a special user and then install (and run) it as that user, but is there anything simpler?
