### ISSUE TITLE
CLI doesn't respect custom appid for transit key

### ISSUE THREAD

**Issue by louiswins** [warner/magic-wormhole#339]
The wormhole CLI takes an appid command-line parameter which it uses when connecting to the relay, but it always derives the transit key from the default appid. It should respect the custom appid for key derivation.

**Comment by warner** [comment]
Huh, that was silly of me:

https://github.com/warner/magic-wormhole/blob/13102d3eeded33a4ad749078de9bbca5000ffbe6/src/wormhole/cli/cmd_send.py#L183-L185

The transit key is derived from the wormhole session key using `w.derive_key`, which is already scoped to the APPID: there's no reason to include it again in the "purpose" argument.

So the ideal fix would be to remove it entirely, and make that call into `w.derive_key("transit-key", ts.TRANSIT_KEY_LENGTH)`. Either way it'd be a compatibility break, so we'd need to do some negotiation ahead of time. And if we're breaking for that, we might as well break for something more valuable like Dilation.

So I'm in complete agreement that this was a mistake, but it doesn't hurt anything, and fixing it would be more trouble than it's worth.

I'm going to change the code to replace that APPID with a local copy, and a note to make it clear that this is an accidental compatibility-critical magic string, pointing back to this ticket.

Thanks for the catch!
