### ISSUE TITLE
Outdated documentation about tor?

### ISSUE THREAD

**Issue by a3nm** [warner/magic-wormhole#367]
Hi,

https://github.com/warner/magic-wormhole/blob/master/docs/tor.md says:

> Unfortunately, at present, Tor support is only available under python2.7. Attempting to install magic-wormhole[tor] (or txtorcon or txsocksx) under py3 results in an inscrutable error that references strings like "vcversioner", "install_requires must be a string or list of strings", and "int object not iterable". Support for py3 will hopefully be added in a future release.

But this links to this issue https://github.com/warner/magic-wormhole/issues/136 which has been closed for 2 years.

Shouldn't this caveat be removed?

**Comment by warner** [comment]
Oops, yes, you're right. I just double-checked and `--tor` support seems to work fine on both py2 and py3. I'll remove the note.. Thanks!

**Comment by meejah** [comment]
Yeah, `txtorcon` has shipped its own SOCKS5 library for a while (since it gained python3 support, because `txsocksx` will not be ported to py3)
