### ISSUE TITLE
autocomplete doesn't work on Mac OS X

### ISSUE THREAD

**Issue by wsanchez** [warner/magic-wormhole#37]
`codes.py` has:
```
readline.parse_and_bind("tab: complete")
```

On OS X, which uses `libedit`, you need:
```
readline.parse_and_bind("bind ^I rl_complete")
```

**Comment by warner** [comment]
For reference, this was helpful:
http://stackoverflow.com/questions/7116038/python-tab-completion-mac-osx-10-7-lion/7116997#7116997
