### ISSUE TITLE
No documentation for running the transit relay

### ISSUE THREAD

**Issue by kaie** [warner/magic-wormhole#387]
Thanks a lot for providing this great utility!

I wanted to run my own transit relay, but found it very difficult to find out how to do it.

I suggest to add the command to run a transit relay to your documentation:

twist3 transitrelay

optionally an a specific port:

twist3 transitrelay --port=tcp:4001

Also it's not clear how to use --blur-usage could you please give an example?

Thanks

**Comment by kaie** [comment]
I just found that you have that in a separate repository magic-wormhole-transit-relay.

I suggest that here in the documentation:
https://magic-wormhole.readthedocs.io/en/latest/welcome.html#relays
you could have a link to
https://github.com/warner/magic-wormhole-transit-relay/blob/master/docs/running.md

**Comment by warner** [comment]
Good idea.. I'll land a fix momentarily. Thanks for the suggestion!
