### ISSUE TITLE
Run (magic-)wormhole  from the Julia REPL works great!

### ISSUE THREAD

**Issue by dietercastel** [warner/magic-wormhole#391]
This isn't much of an issue, but more of a (nice) feature and a thank you.
With a small Julia script (and some awesome libraries) I was able to rune magic-wormhole from the Julia REPL.

```julia
]add Conda
]add PyCall
using Conda
using PyCall
Conda.add("magic-wormhole",channel="conda-forge")
# Once install we're good to go.
os = pyimport("os")
# Conda adds to the the 'base' environment by default
os.system("conda activate base & wormhole send --text mytest")
#or
#os.system("conda activate base & wormhole send 
# or 
#os.system("conda activate base & wormhole receive YOURSTRINGHERE")
```

(Latest version of the) script to be found [here](https://gist.github.com/dietercastel/91aa45ab325ecc95ded8c974c8400cf7)

Thanks for the awesome tool @warner!

**Comment by warner** [comment]
neat! glad it was useful!
