### ISSUE TITLE
overhaul client: reconnect to rendezvous server, move state machine to Automat

### ISSUE THREAD

**Issue by warner** [warner/magic-wormhole#42]
At Glyph's suggestion, I think we should replace the messy ad-hoc state machine in Wormhole to use the [Automat](https://github.com/glyph/automat) module.

**Comment by warner** [comment]
Working on this in my branch `42-automat`. It requires our state machine to be broken up into about 5 or 6 separate state machines, which I think is the intent of Automat anyways.

**Comment by warner** [comment]
Updated the title: the real feature here is that we should survive losing the connection to the Rendezvous server, by re-establishing it and then re-sending whatever we needed to send. At the moment I'm very hesitant to upgrade or reboot the Rendezvous server because it would interrupt any half-opened wormholes in progress. With this change, that should no longer be a problem: as long as the server isn't down for more than 10 or 20 minutes, the clients should be able to sync back up properly. (if it's down for longer than 20 minutes, the server might start pruning the mailboxes for lack-of-use, but it only takes a minute to reboot).

The *Transit* server is another matter, and if it bounces, any relay-using transfers will fail. #88 could cover that, although #88 is currently about human-retriggered retries rather than automatic retries, which would be nice.

**Comment by warner** [comment]
This branch is almost ready, and has turned into a complete rewrite of the client. I've got a grand total of 13 state machines (trying to make each one fairly small, but that didn't always work out).

The branch is now named `42-overhaul`. All tests pass, but I'm still going through to compare functionality against trunk and make sure I'm not regressing anything.

**Comment by warner** [comment]
phew, finally landed it. That was about 4-5 months of work.. I'm glad it's finally done!

I'm going to keep this ticket open until the reconnection functionality is tested (since apparently it doesn't work yet).

**Comment by xsteadfastx** [comment]
Any news on the reconnect?

**Comment by warner** [comment]
Sorry, I should have mentioned, I think reconnection is working. Didn't mean to keep you in suspense!

**Comment by xsteadfastx** [comment]
Is it already in the release or in a branch? I tried wormhole for the first time yesterday and the connection was flaky and there was no reconnection happening. Do I need config any thing?

Am 29. Oktober 2017 11:24:25 MEZ schrieb Brian Warner <notifications@github.com>:
