### ISSUE TITLE
Rendezvous should not send list of in-use nameplates to clients

### ISSUE THREAD

**Issue by Laharah** [warner/magic-wormhole#53]
In a high volume relay, an attacker looking to intercept files can use the `_list` function to find nameplates waiting for a receiver, and use them to attempt file interception. On a high traffic relay, say 2-3 transfers a second, you have about a 30% chance of an intercept over the course of 2 hours. 

If we prevent auto-complete on nameplates however, an attacker would have to guess nameplates to find one with a sender listening. Moreover, if they are rapidly polling low nameplates, legitimate users would be less likely to receive those nameplates from the server, especially if the rate limiting is implemented on lonely nameplates.

**Comment by warner** [comment]
Hm, I have to think about that. I find it really convenient to be able to tab-complete the nameplate id (the number at the start of the wormhole code), so it'd be sad to give that up. And I suspect that removing `list()` wouldn't slow down the rate at which the attacker could probe nameplates very much.

But yeah, if mass-polling of nameplates has the side-effect of preventing them from being allocated by subsequent clients, then that probably helps matters (at least it turns the MitM attack into a DoS attack, which is arguably better).

Removing tab-completion on nameplates would also simplify the code a bit, at the moment there's an awkward interface between the (blocking) readline-based tab-completion handler, and the (async) `list()` handler.

**Comment by Laharah** [comment]
My one worry about rate-limiting is that it does make the relay even *more* susceptible to DOS attacks. It gets back to the problem of figuring out how many digits can a nameplate id have before it's inconvenient, forcing some kind of rollover on the oldest open nameplates. And then balancing that against how much we can rate-limit aborted nameplates before we make it too easy to DOS.

**Comment by warner** [comment]
BTW I'm getting more comfortable with dropping tab-completion for nameplates.. they're pretty short. At the moment I usually type something like `4 TAB p u TAB s a TAB RETURN`, and this would change that into `4 - p u TAB s a TAB RETURN`. Not quite as pinky-bounces-on-TAB friendly (that hyphen is at the far other side of the keyboard), but not too bad.

#150 talks about making this configurable on the server, so some applications could choose to enable tab-completion of nameplates, and others could choose to turn it off.

Another thought I had was to add an attribute to each nameplate, saying whether it was willing to be included in the `list` (nameplates) output or not. Client-selected nameplates could opt out.
