### ISSUE TITLE
tor support is broken when connecting to existing tor process

### ISSUE THREAD

**Issue by warner** [warner/magic-wormhole#64]
While trying to port magic-wormhole's Tor support to Foolscap, I discovered that the "connect to existing Tor" code path doesn't read the SOCKS port from the running daemon the way it's supposed to. It works, but only because the running daemon happens to be using the default SOCKS port (which `txtorcon.TorClientEndpoint` uses when you pass in `socks_port=None`).

What it's supposed to do is to connect to the running daemon, fetch a copy of it's config, then extract `config.SocksPort` and build the `TorClientEndpoint` from that.

**Comment by warner** [comment]
Meejah and I figured this out out Foolscap, so the task is now to port that code into magic-wormhole. Basically if the control port / `TorConfig` socks port is the string `"DEFAULT"`, then just replace it with `9050`.

**Comment by meejah** [comment]
See also: https://github.com/meejah/txtorcon/issues/177

So, there is a mechanism to get the actual default values from Tor, but it won't/doesn't work for the `SOCKSPort` case...
