### ISSUE TITLE
man pages

### ISSUE THREAD

**Issue by jrollins** [warner/magic-wormhole#69]
Most (all?) distros require man pages for binaries that are shipped with packages.  For Debian, we need man pages for wormhole and wormhole-server.  For the initial packaging that I've put together (https://bugs.debian.org/833090) I've made very basic man pages with help2man which do not include any subcommand help.  It would be great if we had a good way to generate man pages directly from the python built-in documentation that included subcommand usage for both wormhole and wormhole-server.

**Comment by warner** [comment]
What's the best format for that? I was thinking about writing some .rst or .md -format docs, and publishing them to ReadTheDocs. But I've also got an overly-clever idea in mind for the web-hosted docs, so they might end up on magic-wormhole.io rather than readthedocs.

I've never written a man page in NROFF, but I've written a handful of things that must have gotten converted into it.

**Comment by jrollins** [comment]
On Mon, Aug 01 2016, Brian Warner <notifications@github.com> wrote:
> What's the best format for that? I was thinking about writing some
> .rst or .md -format docs, and publishing them to ReadTheDocs. But I've
> also got an overly-clever idea in mind for the web-hosted docs, so
> they might end up on magic-wormhole.io rather than readthedocs.
>
> I've never written a man page in NROFF, but I've written a handful of
> things that must have gotten converted into it.

Yeah, this is a good question.  NROFF is annoying, and not very
translate-able.  It would be better if there was a documentation system
that would allow you to write the documentation in something like .rst
or .md and allow you to export NROFF, like help2man.  I can't tell if
sphinx has something that would do that.

I guess we could just write documentation in a format that help2man
could process...

**Comment by jrollins** [comment]
On Wed 2016-08-03 03:35:03 -0400, Jameson Graef Rollins wrote:
> On Mon, Aug 01 2016, Brian Warner <notifications@github.com> wrote:
>> What's the best format for that? I was thinking about writing some
>> .rst or .md -format docs, and publishing them to ReadTheDocs. But I've
>> also got an overly-clever idea in mind for the web-hosted docs, so
>> they might end up on magic-wormhole.io rather than readthedocs.
>>
>> I've never written a man page in NROFF, but I've written a handful of
>> things that must have gotten converted into it.
>
> Yeah, this is a good question.  NROFF is annoying, and not very
> translate-able.  It would be better if there was a documentation system
> that would allow you to write the documentation in something like .rst
> or .md and allow you to export NROFF, like help2man.  I can't tell if
> sphinx has something that would do that.
>
> I guess we could just write documentation in a format that help2man
> could process...

fwiw, pandoc does pretty simple markdown-to-nroff conversion.

I would avoid using help2man or anything else that requires executing
external code though.

     --dkg

**Comment by meejah** [comment]
I wrote all of txtorcon's docs in Sphinx and it's packaged in Debian -- could "whatever Lunar and the currant maintainer did" serve as inspiration? From my end, I didn't change anything -- except getting fewer `id()`'s/memory-addresses in the docs for the reproducible-builds. It looks like something was run to simply convert Sphinx/rst to .txt files (so, not "real man pages" just stuff in /usr/share/doc/python-txtorcon)

Of course, that said, txtorcon is a library not a command...

**Comment by warner** [comment]
Sphinx sounds good to me, that's what readthedocs wants too. I guess we'd have one .rst file with concise how-to-run-the-executable instructions, which gets translated into nroff for the man page, but which would be just one page of the readthedocs docs. Let's call it `docs/running.rst'. (Or .md .. the existing docs are in .md, but I'd be happy to change them to .rst if the X-to-nroff tool wants .rst, so they'd be consistent)

**Comment by meejah** [comment]
Looks like Sphinx supports this directly: http://www.sphinx-doc.org/en/stable/builders.html#sphinx.builders.manpage.ManualPageBuilder

So then you just need one top-level document for `wormhole` and another for `wormhole-server` and "a small matter of configuration" to tell Sphinx which is what. (See also I guess, https://wiki.debian.org/Python/LibraryStyleGuide for the command that's suggested while packaging for debian).

Sphinx uses rST, period as I understand.

**Comment by anarcat** [comment]
sphinx supports rst, indeed, but the result is not exactly nroff-canon and "standard", but it could be considered good enough.

more solid alternatives are generally based on markdown:

* https://sunaku.github.io/md2man/man/man0/README.html
* http://rtomayko.github.io/ronn/

It's interesting to note that readthedocs also supports markdown parsers now, so you could include those in the documentation as well. ronn is packaged in debian as ruby-ronn.

**Comment by anarcat** [comment]
fwiw, @jrollins wrote manpages for the two commandline tools here:

https://sources.debian.net/src/magic-wormhole/0.8.1-1/debian/wormhole.1/
https://sources.debian.net/src/magic-wormhole/0.8.1-1/debian/wormhole-server.1/

i'd be happy to make a pull request to merge those in upstream unless you want to use the aforementionned rst/md2man solutions...

**Comment by warner** [comment]
I'm happy to have .nroff temporarily, until we get something more sustainable (in markdown). Please PR away :).

**Comment by anarcat** [comment]
@warner ok, see #102 for now.
