### ISSUE TITLE
overwrite existing file when --output-file= is provided

### ISSUE THREAD

**Issue by warner** [warner/magic-wormhole#73]
A suggestion by `@teufen` on twitter: allow some way for the receiving user to allow an existing target file to be overwritten. This is especially useful if you're running the same `wormhole send` multiple times (with a newer version of the file).

It's not safe, in general, to overwrite existing files, especially because the filename is being selected by the sender. But we could give the receiver a way to opt-in to the overwrite, if it's happening predictably. And the existing `--output-file=` option is a pretty clear and predictable signal: any overwriting is going to affect a single user-specified path.

So the rule would be that if the recipient receives a file that already exists, but the filename came from `--output-file=`, then print a `overwriting FILENAME` message and overwrite it.

TBD: what to do when `--output-file=` is a directory: do we `rm -rf` the old directory and replace it entirely? (also, maybe this suggests that `--output-file=` is misnamed, if it could refer to directories)

**Comment by horak** [comment]
So if I understand this thread correctly, `wormhole send --output-file <directory name>` is not at this point supported?
