### ISSUE TITLE
'Torrent' mode?

### ISSUE THREAD

**Issue by takluyver** [warner/magic-wormhole#80]
This is probably far-fetched, but wormhole seems like an interesting base for this idea:

Rather than 1-to-1, could we efficiently do 1-to-many transfer of a file - possibly with torrenting for extra efficiency?

I'm in a conference tutorial, where ~200 people are trying to download the same tutorial materials over wifi at once, and soon the download speeds make dial-up look good. We resorted to passing around USB sticks for some files this morning. Surely, in the 21st century, we can do better than this!

Bittorrent would probably work, but half the room would first need to download multi-MB torrent clients, set them up on a range of different platforms, then work out how to start the torrent. Assuming people have Python (OK, I'm at a Python conference :-), wormhole is a couple of instructions that are the same on any platform:

```
pip install magic-wormhole
wormhole recv 8-foo-bar
```

**Comment by warner** [comment]
Hm, interesting! That's certainly a great use-case.

The PAKE algorithm doesn't really support multiple connections, though. The security comes from it being a single-use code, so if the sender is willing to re-use the same code for 200 connections, we'd be giving an attacker 200x the chance to guess it. I could imagine a mode where it'd accept multiple connections as long as each of them succeeded (i.e. make connections one at a time, when one succeeds, allow the next one to start, but terminate immediately upon the first failure and don't accept any subsequent attempts). I think that'd mitigate the attack-multiplier, but the usability would suffer. I'd feel pretty bad being the audience member who fumbled the code and then forced the presenter to restart the process and announce a new code.

If we weren't trying to make it secure, we could use the code (in fact just the channel-id) as a broadcast-channel identifier, and everybody would just get whatever they get. It's probably ok to give up confidentiality for a broadcast like this, but it'd be nice if an attacker couldn't break integrity (modifying the tutorial en-route).

Let's see, what protocols/tools could we use to maintain integrity? The only thing I can think of is:

* publish the channel-ID and a hash of the file, everybody downloads the file and then manually compares the hash. Maybe after everyone has downloaded it, the presenter reads out the hash, and everybody compares it against what's on their screen

Any other ideas?

For the actual transmission of the bits, Bittorrent would be a great distribution mechanism, and whatever we come up with for the PAKE/wormhole side could just be responsible for distributing the .torrent metadata file. But I totally agree that actually integrating a BT client into this tool would be a big hassle. Is there any pure-python Bittorrent implementation out there?

**Comment by takluyver** [comment]
Yes, thinking about it some more, what I really want is the convenient interface of magic-wormhole for sending and receiving files - and especially for directories without needing a separate tar/zip tool to unpack them. The PAKE algorithm it's based around isn't really relevant for this, so maybe it would be best developed as a separate tool.

I agree that, at least for my use cases, confidentiality isn't important, but it would be nice to preserve integrity.

I'm not wild on manual hash comparisons - I think people will just skip it, leaving it insecure in practical terms. Ideas I've come up with:

- Download a hash (possibly in the form of a torrent file) from an HTTPS URL based on the code the user enters. An attacker cannot modify the data at the URL, or intercept the requests. This still requires each recipient to download something the normal way, but hopefully that can be kept quite small.
- The code that's advertised is a truncated hash of the file contents, strengthened by using the kind of key-derivation function used for passwords storage. For this kind of application, it's reasonable for verification to take a few seconds on the slowest hardware in the room. Integrity relies on attackers not being able to find a collision for even the truncated hash quickly enough to be useful. Getting the tuning right to balance security, verification time and code length is tricky, though.

For phones we'd probably use QR codes, but that's awkward for laptops. Maybe something is possible with sound, though that's probably fiddly to make work.

**Comment by takluyver** [comment]
Oh, and there are a few pure-Python implementations of bittorrent out there, but none of the ones I found look actively maintained:

- https://github.com/wickman/rainman
- https://github.com/abhijeeth/AutonomoTorrent
- https://en.wikipedia.org/wiki/BitTornado

rainman looks the most promising if I were to try to build something.

**Comment by Porco-Rosso** [comment]
@takluyver your use case is well covered by the upcoming IPFS protocol

https://youtu.be/HUVmypx9HGI?t=19m59s

https://ipfs.io/

**Comment by takluyver** [comment]
I've looked at IPFS before - it's very cool technology, and I could certainly see the protocol being part of a solution. But the main implementation of IPFS requires too much set up to be usable for what I want.

There are two particular requirements for this use case that made me think of wormhole, even though it's not actually the tool for the job:

- Small download and simple installation (this relies on people having Python, but it was a Python conference that prompted the idea ;-)
- Easy to use - no daemons to run, nothing to configure, just type one command and it downloads a whole directory.

I'll close this issue now - I want something like wormhole's UI, but with quite a different functionality behind it.
