### ISSUE TITLE
README should add 'sudo apt-get install python-pip' and 'sudo pip install service_identity' to package install list

### ISSUE THREAD

**Issue by grempe** [warner/magic-wormhole#89]
To install on a Raspberry Pi  (and maybe other debian distros) I needed to also do:

`sudo apt-get install python-pip`

I also saw the following error on first use:

```
$ wormhole receive
:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named service_identity'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module and a recent enough pyOpenSSL to support it, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
Enter receive wormhole code: 4-retrieval-atlas
Receiving file (1253 bytes) into: cert.pem
ok? (y/n): y
...
```

Running `sudo pip install service_identity` resolved this issue on future runs.

**Comment by meejah** [comment]
In general, you should never run `pip` as root.

Instead, use `virtualenv` to create a "virtual [python] environment" into which you can install wormhole (and dependencies). Perhaps the README should be more explicit about this.

**Comment by warner** [comment]
Thanks for the catch.. I'll mention `python-pip` in the README.

I'm puzzled by the `service_identity` error, though.. I didn't think the code would ever get into a situation where it needed that. Are you running the current version of magic-wormhole (0.8.1)?

(we could declare a dependency upon `twisted[tls]` to ask it to install `service-identity`, but until we start using TLS to the rendezvous server, I don't think we need it)

**Comment by grempe** [comment]
v0.8.1 on both sides. Sorry I'm not much help here. I never use Python. Perhaps the `service-identity` warning was just that, a warning, and not a requirement. I don't remember if I tried to run it before following up on that warning and installing it. In either case it might merit a mention in the readme. Feel free to close if thats the case.

## On Raspberry Pi

Note the default permissions when installing this package require `sudo`.

```
$ uname -a
Linux rp1 4.4.26-v7+ #915 SMP Thu Oct 20 17:08:44 BST 2016 armv7l GNU/Linux

$ pip show magic-wormhole
---
Name: magic-wormhole
Version: 0.8.1
Location: /usr/local/lib/python2.7/dist-packages
Requires: autobahn, click, six, spake2, twisted, hkdf, tqdm, pynacl

$ ls -la /usr/local/lib/python2.7/
total 16
drwxrwsr-x  4 root staff 4096 Sep 27 14:06 .
drwxrwsr-x  4 root staff 4096 Aug 11 22:51 ..
drwxrwsr-x 35 root staff 4096 Nov  3 15:13 dist-packages
drwxrwsr-x  2 root staff 4096 Sep 27 14:06 site-packages
```

## macOS (Sierra)

```
$ pip show magic-wormhole
Name: magic-wormhole
Version: 0.8.1
Summary: Securely transfer data between computers
Home-page: https://github.com/warner/magic-wormhole
Author: Brian Warner
Author-email: warner-magic-wormhole@lothar.com
License: MIT
Location: /usr/local/lib/python2.7/site-packages
Requires: autobahn, twisted, hkdf, spake2, click, tqdm, pynacl, six
```

**Comment by SpEcHiDe** [comment]
@grempe I think the reason for that error might be caused because your system date in the RPi is wrong.

**Comment by grempe** [comment]
@SpEcHiDe I'm not sure why a bad time would cause a request to install a package. Of course I can't go back in time to check the state the RPi was in at the moment, but I do run ntpd on that device. It currently reports time in sync, which I am pretty sure it would have been when I reported this as well.

```
~ $ ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
+4.53.160.75     142.66.101.13    2 u   54 1024  377   75.685   -5.710 221.987
+2.202.196.104.b 128.138.141.172  2 u  443 1024  377   93.236   -1.121  32.146
+quirk.faceprint 18.26.4.105      2 u  965 1024  377  102.262   -4.147 203.647
*dns2.untangle.c 216.218.254.202  2 u  544 1024  377   63.192   18.058  23.495

~ $ date
Wed Dec  7 00:14:30 PST 2016
```

**Comment by warner** [comment]
It looks like modern Twisted tests for `service_identity` as soon as `twisted.internet.endpoints` is imported, which magic-wormhole does all the time. So even though we aren't yet using TLS, we need it installed to avoid the warning.

I guess I'll change the twisted dependency to be `twisted[tls]`, which will pull in service-identity (or whatever other libraries Twisted decides it needs in the future). That will pull in a bunch of new requirements (some ASN1 modules, `pyopenssl`, and `cryptography` which has binary components), which is a drag. But I guess we'll be moving the rendezvous server connection to TLS eventually, just on general principles, so we might as well bite the dependency bullet now.
