### ISSUE TITLE
do not attempt to download without required free space

### ISSUE THREAD

**Issue by anarcat** [warner/magic-wormhole#91]
i have had the bad experience of downloading 2.2 GB of data and then discovering i actually needed 2.3GB of free space on disk to download the whole file. the discrepency was due to an operator mistake in calculating (in my head) how much 2633026488 bytes were... (obviously, it would be nice to show human readable file sizes, but that's beside the point here).

wormhole shouldn't attempt to download a file that will fill the disk, because it will fail and it can't resume (#88).

**Comment by warner** [comment]
Sounds reasonable to me, I'd accept a patch. I don't know how hard it is to do it right, though.. in Tahoe we did something similar, and it works horrendously differently on windows (see [allmydata.util.fileutil.get_disk_stats](https://github.com/tahoe-lafs/tahoe-lafs/blob/master/src/allmydata/util/fileutil.py#L443)). Alternatively we could just do `open(); seek(SIZE); write("\x00"); seek(0)`, but if the platform supports sparse files, that won't actually fail. We could do `write("\x00" * size)` (or a less memory-hungry equivalent), but that'd introduce a significant delay for large files. I can imagine having some highly asynchronous receiver running a loop that tries to populate the whole file (with zeros), and then when each new record arrives over the wire, it seeks back to the right place and writes the record, then seeks back to the end and keeps appending: that would avoid the delay, and would still fail earlier than before, but would still fail "late" sometimes, and the state machine would be kinda heinous.

The deeper problem is that we can't know the size of the incoming file until we've consumed the code, so the sender will always have to start again (and the receiver will always have to ask the sender to start again, which is a big crimp in the workflow). I have some ideas in mind for resumable transfers, but they'll depend upon using the same sending and receiving machines (it'll store a full-sized key in some small file on both of them).

**Comment by anarcat** [comment]
On 2016-11-11 19:22:05, Brian Warner wrote:
> Sounds reasonable to me, I'd accept a patch. I don't know how hard it is to do it right, though.. in Tahoe we did something similar, and it works horrendously differently on windows (see [allmydata.util.fileutil.get_disk_stats](https://github.com/tahoe-lafs/tahoe-lafs/blob/master/src/allmydata/util/fileutil.py#L443)). Alternatively we could just do `open(); seek(SIZE); write("\x00"); seek(0)`, but if the platform supports sparse files, that won't actually fail. We could do `write("\x00" * size)` (or a less memory-hungry equivalent), but that'd introduce a significant delay for large files. I can imagine having some highly asynchronous receiver running a loop that tries to populate the whole file (with zeros), and then when each new record arrives over the wire, it seeks back to the right place and writes the record, then seeks back to the end and keeps appending: that would avoid the delay, and would still fail earlier than before, but would still fail "late" sometimes, and the state machine would be kinda heinous.

maybe the degenerate case should be that windows fails as it does now
and platforms that make sense have the extra feature of detecting free
space. :)

**Comment by warner** [comment]
I would be totally ok with that :)

**Comment by warner** [comment]
@anarcat take a look at #96 and see if it works the way you'd like

**Comment by anarcat** [comment]
that's probably right, although i haven't reviewed all the specifics.

the root vs regular user is a tough call: i'd say you made the good one because we don't want to fail if we can succeed (e.g. if we run as root, allow foot-shooting)...

**Comment by meejah** [comment]
So as a slightly contrarian point of view, and *especially* given the "one time" nature of the wormhole setup, perhaps a warning would be better? e.g. "it doesn't seem you have enough disk space, better start deleting some tempfiles before I fill it up entirely".

Also, it's "probably" going to take many dozens of minutes to download "gigabytes" so a real user would likely have time to go and delete their oldest cat-photos or whatever. (Similarly, even if you check first, they may be busily filling up the disk with logs or SQL dumps or whatever in the meantime anyway).

Even better than just failing prematurely would be to pause: "I have paused the transfer because we're about to fill up the disk; please free up some space or ctrl-c" and then check again every 10 seconds or something and if there's more space resume the transfer.

**Comment by cariaso** [comment]
agreeing with @meejah . I have an infinite disk
https://github.com/awslabs/amazon-ebs-autoscale
and I'd like to use wormhole on it, but I can't. 
I could prewarm, but I can't know the necessary size until the transfer has begun. There seems to be no way to disable this check.

please consider a `--force` or similar to bypass this check.
