### ISSUE TITLE
receive hangs with empty file

### ISSUE THREAD

**Issue by joeyh** [warner/magic-wormhole#98]
I've noticed that the special case of the empty file often exposes interesting bugs in stuff, and it seems to have with wormhole:

joey@kite:/tmp>touch bob
joey@kite:/tmp>wormhole send /tmp/bob
Sending 0 byte file named 'bob'
On the other computer, please run: wormhole receive
Warning: errors may occur unless both sides are running the same version
Server claims 0.8.2 is current, but ours is 0.8.1
Wormhole code is: 2-souvenir-retouch

Sending (<-66.228.36.95:47154)..
0.00B [00:00, ?B/s]
File sent.. waiting for confirmation

In another terminal:

joey@kite:~>wormhole receive
Warning: errors may occur unless both sides are running the same version
Server claims 0.8.2 is current, but ours is 0.8.1
Enter receive wormhole code: 2-souvenir-retouch
Receiving file (0 bytes) into: bob
ok? (y/n): y
Receiving (->tcp:66.228.36.95:41551)..
0.00B [00:00, ?B/s]

Seems to have hung indefinitely at this point.

**Comment by warner** [comment]
Heh.. good catch. I bet there's something that checks for completion status after the transfer of each chunk of data, but if there never were any chunks, it never gets called, and then never gets a chance to declare success.

I'll look to see how hard it is to fix this properly. If it's too much of a hassle, I'll just special-case the 0-length file and have it skip the Transit setup or something.
