### ISSUE TITLE
receive UI output to stdout, use stderr instead

### ISSUE THREAD

**Issue by joeyh** [warner/magic-wormhole#99]
I want to use wormhole to exchange addresses and authentication data when linking two peers over tor. It seems to make most sense to send the data over the wormhole as a message, rather than as a file, since it's short and sensitive.

But, wormhole receive outputs the message, including "Enter receive wormhole code:" to stdout.  I suggest making all such stuff be sent to stderr, so that stdout can be captured to get the whole message and nothing else.

**Comment by warner** [comment]
yeah, good idea. I remember doing this for several messages, but I guess I failed to do it more generally.
